### ISSUE TITLE
bug report battery box jumping

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#100]
**Describe the bug**
[A clear and concise description of what the bug is.]
while many items work by mop fine the battery box item is not properly loaded and unloaded by the mop and as a result, they jump around any shelve/table they get put on the house
**To Reproduce**
[Steps to reproduce the behaviour:
1. purchase batteries from Teimo (the box)
2. move these battery boxes either to your office desk in your room or the kitchen table or the shelve in the entrance 
3. move far way and come back (teleporter tool can also be used)
4. see the error some of the battery boxes have jumped around even launching themselves on the floor

**Expected behaviour**
[A clear and concise description of what you expected to happen.]
the battery boxes just like many items would not move at all or very little
**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go in to mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-07-05_14-22.zip](https://github.com/Athlon007/MOP/files/9045940/MOP.Bug.Report.-.2022-07-05_14-22.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Can't replicate

**Comment by tonimark** [comment]
> Can't replicate

IMPORTANT UPDATE: it turns out going way and coming back doesn't replicate it BUT
if you save the game to the menu and then load the game then it happens. this bug doesn't occur normally but it occurs only at mop initialization when you load the game

**Comment by BuoYancYdabl** [comment]
Can only confirm that it occurs on vanilla version, MOP is not a reason of it!

**Comment by Athlon007** [comment]
> > Can't replicate
> 
> IMPORTANT UPDATE: it turns out going way and coming back doesn't replicate it BUT if you save the game to the menu and then load the game then it happens. this bug doesn't occur normally but it occurs only at mop initialization when you load the game

Alright, now I can reproduce it sometimes. I'll try to address it in the next update.

**Comment by Athlon007** [comment]
Fixed in 3.8.1.
