### ISSUE TITLE
bug report satsuma's exhaust muffler will be dettached if the player teleport near it 

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#101]
**Describe the bug**
[A clear and concise description of what the bug is.]
I was suspecting a bug in the mop that would constantly detach the satsuma's exhaust muffler from the car then when I picked up my cousin and died I heard a part detaching, and just I suspected it was the exhaust muffler again...  
so I decided to report this bug
(most likely dying and having the satsuma parked in the garage)
**To Reproduce**
[Steps to reproduce the behaviour:
1. install the exhaust muffler in the satsuma
2. move far way
3. teleport back to the satsuma (in my case the satsuma was in the garage and I died) , this won't work if you approach the car from distance
4. See error the muffler has been detached 

**Expected behaviour**
[A clear and concise description of what you expected to happen.]
the satsuma muffler would still be installed and intact
**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
[MOP Bug Report - 2022-07-05_14-50.zip](https://github.com/Athlon007/MOP/files/9046114/MOP.Bug.Report.-.2022-07-05_14-50.zip)

**Comment by Athlon007** [comment]
I've tried, but I cannot reproduce it.

**Comment by tonimark** [comment]
I got an idea if you park the satsuma too close to home and then die(so you teleport at home) then the exhaust will come off, I also couldn't replicate it by teleporting alone,death also needed

**Comment by Athlon007** [comment]
Yup, now I can reproduce it.

**Comment by Athlon007** [comment]
Fix 3.8
