### ISSUE TITLE
Satsuma not loading properly.

### ISSUE THREAD

**Issue by TheDevil6678** [Athlon007/MOP#102]
Hi Athlon007,

before pointing out my problem I just want to tell you that I'm Magician - the guy who told you about the 32bit version of the game where you thought is outdated (when I may had issue again but I don't remember with what). Anyways, my problem is that the half of my car doesn't want to load. I tried disabling every single mod and it still don't work. I'm not in hurry and help me when you can because I know you're very busy person and I always respect everyone's schedule and time.

[MOP Bug Report - 2022-07-07_10-12.zip](https://github.com/Athlon007/MOP/files/9061308/MOP.Bug.Report.-.2022-07-07_10-12.zip)

Your friend, Magician.
I have new Discord btw if you decide to message me personally: СТОЯН КОЛЕВ#6996

**Comment by Athlon007** [comment]
Hello,
Unfortunately, I was unable to reproduce the issue. The car loads fine for me:
![1](https://user-images.githubusercontent.com/24318504/177751892-064aab47-faac-4b5a-a884-d64e662be085.png)

**Comment by TheDevil6678** [comment]
Strange, because for me even the dashboard and that stuff isn't loading.
Ok, I will check again what I can do. Thanks in advance, Athlon007!

**Comment by Athlon007** [comment]
Yeah, I'm sorry, but it's nearly impossible for me to fix a bug that I can't reproduce :(

**Comment by Athlon007** [comment]
Fix in 3.7.2
