### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ekubambam** [Athlon007/MOP#103]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
[MOP Bug Report - 2022-07-10_00-56.zip](https://github.com/Athlon007/MOP/files/9077998/MOP.Bug.Report.-.2022-07-10_00-56.zip)
when i enter the game hayosoki and all of the engine,car parts disappears

**Comment by Athlon007** [comment]
Sorry, but illegal copies of My Summer Car are not supported.
