### ISSUE TITLE
Found a problem with the newest update.

### ISSUE THREAD

**Issue by LogitechGHUBisBAD** [Athlon007/MOP#104]
When i want to order something using the Amis Auto catalogue, the envelope does not appear after selecting the items i want to order.

To Reproduce:
1. Go into amis catalogue
2. Select items
3. Click order, or something like that.
4. Envelope does not spawn.

here is the file.
[MOP Bug Report - 2022-07-11_21-27.zip](https://github.com/Athlon007/MOP/files/9087073/MOP.Bug.Report.-.2022-07-11_21-27.zip)

**Comment by Athlon007** [comment]
I've tried it - the envelope spawns fine for me.
Are you sure you don't have the envelope somewhere already?
