### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by wailmers115** [Athlon007/MOP#105]
[MOP Bug Report - 2022-07-12_09-08.zip](https://github.com/Athlon007/MOP/files/9088636/MOP.Bug.Report.-.2022-07-12_09-08.zip)
**Describe the bug**
After opening a game. My save game is gone. Can you help me recover it?

**To Reproduce**
[Steps to reproduce the behavior:
![Screenshot (169)](https://user-images.githubusercontent.com/109119787/178388833-8e853722-5996-4c96-ac40-f4e938bbbf52.png)

4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Did you play with mortality enabled?

**Comment by Athlon007** [comment]
By reading the log data, it seems like your save file was corrupted beforehand, as MOP was unable to read important save values.

As for recovering the save, unfortunately, unless you had your own backups - there is not much that can be done.

**Comment by wailmers115** [comment]
Ok, thanks.
