### ISSUE TITLE
Vodka Shot Physics

### ISSUE THREAD

**Issue by BSalgad0** [Athlon007/MOP#106]
It has the exact same bug as the coffee cup and, the physics don't work and after you buy it, it floats in the sair.

Go to teeimo's bar , buy vodka shot, after you drink it bugs in the air.

![image](https://user-images.githubusercontent.com/107504359/178816920-bd03ff13-bf08-4549-9596-bf75b15e853a.png)

[MOP Bug Report - 2022-07-13_20-33.zip](https://github.com/Athlon007/MOP/files/9105385/MOP.Bug.Report.-.2022-07-13_20-33.zip)

**Comment by Athlon007** [comment]
Yup, will be fixed in the next update.

**Comment by Athlon007** [comment]
Fix 3.8.
