### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kawasaki-bayou** [Athlon007/MOP#108]
okay so i was driving and i was only going 30 KHM and i went over the railroad tracks and it almost felt like a invisible wall hit me
its happend whlie i was rallying too i went over a bump and i didn't even get a hard hit to the ground and it acted like i hit a invisible wall  

i dont know if this is a bug or not but its happend quite alot
in the satsuma

![1](https://user-images.githubusercontent.com/85509690/179302066-3290bae1-b41a-4743-9d05-4a3c8179a09e.PNG)
![2](https://user-images.githubusercontent.com/85509690/179302073-35792f4b-803e-4a68-a5cf-4cb986e11d8e.PNG)

heres a screenshot of both events that happend

**Comment by Athlon007** [comment]
What is the average frame rate that you have? Also please generate mod report and send it here.

**Comment by BuoYancYdabl** [comment]
Try avoid using mods that can collide while detaching like bumpers. Sometimes this happens with fenders being detached and collide with satsuma.

**Comment by Athlon007** [comment]
Closed, as necessary info has not been provided.
