### ISSUE TITLE
Satsuma Body corrupted

### ISSUE THREAD

**Issue by putangina-mo** [Athlon007/MOP#109]
for some reason if I make a distance to the satsuma, this bug will occur
[MOP Bug Report - 2022-07-19_11-25.zip](https://github.com/Athlon007/MOP/files/9137191/MOP.Bug.Report.-.2022-07-19_11-25.zip)

![Screenshot (839)](https://user-images.githubusercontent.com/59129601/179658738-7d867642-dcc5-4e34-994c-766cbe317ff7.png)

I deserve a new cpu as a refund if this bug didn't get fixed
and I did bought the game in steam
![image](https://user-images.githubusercontent.com/59129601/179659106-7d9a6d57-2e72-4162-ab86-e7b422679ed4.png)

Specs:
i3 4170
1650 super
16gb ddr3 1600 (2x8)
hyperk 500w

**Comment by Athlon007** [comment]
I honestly don't know, I suspect that might be a mod conflict. 

Perhaps the handbrake mod?

**Comment by putangina-mo** [comment]
well I am not too sure about that. Perhaps give it a support?

**Comment by Athlon007** [comment]
I'm sorry, but I have no clue which mod may cause the issue. I have no time to download 59 mods and trying to find which one is causing the issue.

Needs more info which mod is causing the issue.

**Comment by putangina-mo** [comment]
oh ok

**Comment by MilesDipperion** [comment]
This glitch and the inability to tow vehicles mentioned in issue #120 also occur on clean game with MOP only installed.
[MOP Bug Report - 2022-08-09_17-28.zip](https://github.com/Athlon007/MOP/files/9291643/MOP.Bug.Report.-.2022-08-09_17-28.zip)

**Comment by BuoYancYdabl** [comment]
First of all - stop being so rude and expect the world to turn around you. No one will instantly buy you anything or SHOULD do. This mod comes as free to use and dont have any guarantee. If it was kind of a joke you could atleast after all of that say that.

**Comment by putangina-mo** [comment]
well, you see it as a rude way. It was a joke and I am never gonna let any random people pay for me.

**Comment by Athlon007** [comment]
Please try 3.8.1.

**Comment by putangina-mo** [comment]
ah ok, i was busy practicing

**Comment by putangina-mo** [comment]
Unfortunately, I don't think it works. The body of the satsuma can't move until I push it (the same problem occurs with the previous update). What were the changelog anyway?

**Comment by Athlon007** [comment]
> Unfortunately, I don't think it works. The body of the satsuma can't move until I push it (the same problem occurs with the previous update). What were the changelog anyway?

Could you please pack your Mods folder, and your entire Save file and send it to me at aathlon@outlook.com?

**Comment by putangina-mo** [comment]
Ah, sure.

**Comment by putangina-mo** [comment]
did you receive the email?

**Comment by Athlon007** [comment]
Yes, and unfortunately - the bug doesn't happen for me. I'll try on another computer.

**Comment by Athlon007** [comment]
FINALLY. I got it to trigger on another computer.

**Comment by putangina-mo** [comment]
AH okie

**Comment by Athlon007** [comment]
3.8.2 beta's out.

**Comment by Athlon007** [comment]
Fixed in 3.8.2

**Comment by putangina-mo** [comment]
yay
