### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NightGmk** [Athlon007/MOP#110]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:

4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings 
[MOP Bug Report - 2022-07-21_15-47.zip](https://github.com/Athlon007/MOP/files/9159074/MOP.Bug.Report.-.2022-07-21_15-47.zip)
and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
i have cheatbox mod installed and when i try to teleport satsuma to m it doesn't and when i disabled the modrn optimization it teleported can you fix this?

**Comment by Athlon007** [comment]
Cheatbox Satsuma teleporting is not supported.
