### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by redarmy275** [Athlon007/MOP#111]
**Describe the bug**
Just installing a bunch of mods, here's my mod list :
- Attachable Roofrack
- Delivery Jobs
- Garage Pit Cover
- Wooden Jug Crate
- Minimap
- Mod shop
- Rent Apartment
- Show Bolt Size
- Transport Trailer
- Trailer Hitch System
And it crashes the MOP

**Additional context**
[MOP Bug Report - 2022-07-22_11-18.zip](https://github.com/Athlon007/MOP/files/9164659/MOP.Bug.Report.-.2022-07-22_11-18.zip)

[Add any other context about the problem here.]

**Comment by redarmy275** [comment]
okay thanks

**Comment by redarmy275** [comment]
> http://athlon.kkmr.pl/mop/

installation path???

**Comment by Athlon007** [comment]
Unpack the file into MSC Mods Folder -> Config -> Mod Settings -> MOP


On 22 Jul 2022, at 19:55, redarmy275 ***@***.***> wrote:

﻿

http://athlon.kkmr.pl/mop/

installation path???
