### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DENIX2XXX** [Athlon007/MOP#112]
bodyparts of the satsuma are getting misplaced as the car deleting, and there's no access to it after. it is clearly mop's problem, that showed up after update from 3.7.2 to 3.8. w/o mop, problem goes away.

![image](https://user-images.githubusercontent.com/109968930/180791143-2adbe7b4-d0f4-43c0-9ffd-8ec57d625ebe.png)
![image](https://user-images.githubusercontent.com/109968930/180791231-ee05f10b-3ee8-48ed-b89c-fa1b837691d4.png)

[MOP Bug Report - 2022-07-25_16-33.zip](https://github.com/Athlon007/MOP/files/9181685/MOP.Bug.Report.-.2022-07-25_16-33.zip)

**Comment by Athlon007** [comment]
Hi there, the save file is missing from the report - could you generate the new bug report WITH the save file and try again?

**Comment by Athlon007** [comment]
Related to #109
