### ISSUE TITLE
Unable to remove save file attributes

### ISSUE THREAD

**Issue by Jeppyishere** [Athlon007/MOP#115]
[MOP Bug Report - 2022-07-28_22-25.zip](https://github.com/Athlon007/MOP/files/9215600/MOP.Bug.Report.-.2022-07-28_22-25.zip)
Hi athlon007, i have a problem with MOP, the game console says that MOP has crashed
and I don't know why, I would like you to fix this error.

Goodbye

**Comment by Athlon007** [comment]
Does that issue occur all the times? It seems like you don't have a permission to your save file.

**Comment by Athlon007** [comment]
Closed due to inactivity.
