### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by MarioElNe** [Athlon007/MOP#116]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]
[MOP Bug Report - 2022-07-29_20-31.zip](https://github.com/Athlon007/MOP/files/9223920/MOP.Bug.Report.-.2022-07-29_20-31.zip)

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
According to the logs, you are using MOP 3.3.10. Please try updating to the latest release.
