### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ThisMavoGuy** [Athlon007/MOP#117]
**Describe the bug**
So i start up my summer car and continue my game and mop starts loading but says it didnt load in time, then it 'stops working' and tries restarting 3 times. then it just says it failed to restart and goes into safe mode

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-07-30_16-23.zip](https://github.com/Athlon007/MOP/files/9225481/MOP.Bug.Report.-.2022-07-30_16-23.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
I'm sorry, but you're using the game version from 2019 (**VERY** outdated).
