### ISSUE TITLE
Bug Report - Unable to tow Satsuma

### ISSUE THREAD

**Issue by Foxal812** [Athlon007/MOP#120]
**Describe the bug**
I cannot tow the Satsuma with MOP enabled in my Mod Menu. 
I can connect the car to the Gifu with the towing cable, but the Satsuma will stay in place and will not move.
When I drive off with the Gifu, with the Satsuma attached, the Car won't move from its spot, as if someone nailed it to the ground.
I have disengaged the handbrake and put the car in neutral, yet I still can't tow the Car, despite being able to push it with my Hands.

**To Reproduce**
1. Park Gifu in front of Satsuma.
2. Connect Towing Cable to Satsuma and Gifu.
3. Release the Handbrake of the Satsuma and put it in neutral.
4. Get in the Gifu and drive off.
5. ERROR: Satsuma might rotate, Towing Cable will disconnect, and Satsuma won't move.

**Expected behavior**
The Satsuma will roll.

**Screenshots**
Video: https://imgur.com/a/zH9aK70

**Mod Report:**
[MOP Bug Report - 2022-08-02_17-26.zip](https://github.com/Athlon007/MOP/files/9243653/MOP.Bug.Report.-.2022-08-02_17-26.zip)

**Additional context**
I really like what you are doing. You are doing an amazing job for not only creating but also maintaining this mod.
Also, I hope that you are having a wonderful day. You deserve it :)

**Comment by Athlon007** [comment]
Yup, can confirm. Will be fixed in the next update.

**Comment by Athlon007** [comment]
Fixed in 3.8.1.

**Comment by Foxal812** [comment]
Thank you :)
