### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Kamil0601PL** [Athlon007/MOP#123]
Dzień dobry, gdy grałem w grę My Summer Car i uruchomiłem modyfikację MOP i uruchomiłem grę wyskoczył błąd i w konsoli pisało to 
![image](https://user-images.githubusercontent.com/82103364/184259910-cb2f9504-1a30-4ad9-86cd-db800c5030c3.png)

Myślałem że gdy odpalę modyfikację będę miał więcej FPS'ów lecz się myliłem i zamiast mieć więcej to miałem wielkie spadki od 30 fps'ów do nawet 10

Tutaj przesyłam raport MOP
[MOP Bug Report - 2022-08-12_01-31.zip](https://github.com/Athlon007/MOP/files/9312668/MOP.Bug.Report.-.2022-08-12_01-31.zip)

Mam nadzieję że otrzymam pomoc i z góry Dziękuje Pozdrawiam

**Comment by Athlon007** [comment]
Przepraszam, ale wygląda na to, że używasz pirackiej kopii gry. Pirackie kopie nie są wspierane, ze względu na brakujące w nich rzeczy, a MOP celuje tylko w najnowszą wersję Steamową.

**Comment by Kamil0601PL** [comment]
Okej dziękuję za pomoc
A za niedługo będę kupował pełną wersję więc na pewno użyje waszego moda

Pozdrawiam


pon., 15 sie 2022, 12:12 użytkownik Konrad Figura ***@***.***>
napisał:
