### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by thedude3253** [Athlon007/MOP#126]
**Describe the bug**
I'll be honest I have no idea. MOP told me an error occurred and to please submit a bug report about it. I thought I'd do the right thing and send it off. Sorry if this is useless to y'all

**To Reproduce**
Not exactly sure. I died on a permadeath save when MOP gave me the message about a crash

**Expected behavior**
I imagine it isn't supposed to encounter an error on the title screen

**Mod Report:**
[MOP Bug Report - 2022-08-15_20-07.zip](https://github.com/Athlon007/MOP/files/9343846/MOP.Bug.Report.-.2022-08-15_20-07.zip)

[MOP_Crash_2022-08-15-20-06.txt](https://github.com/Athlon007/MOP/files/9343844/MOP_Crash_2022-08-15-20-06.txt)

**Comment by Athlon007** [comment]
Thanks for reporting this. Will be fixed in the next update.

**Comment by Athlon007** [comment]
Fixed in 3.8.1.
