### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by MrZega** [Athlon007/MOP#127]
**Describe the bug**
The new update for MOP is now causing the game to freeze when I hit "continue" 

**To Reproduce**
[Steps to reproduce the behavior:
[MOP Bug Report - 2022-08-16_15-51.zip](https://github.com/Athlon007/MOP/files/9355175/MOP.Bug.Report.-.2022-08-16_15-51.zip)

4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Could you please click Continue, then when the game freezes, ALT+F4 from it and upload the "output_log.txt"?
