### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ReptileTextile** [Athlon007/MOP#129]
**Describe the bug**
I bought batteries and opened up the bag at the counter, console popped up saying that an error occured.

**To Reproduce**
1. Go to Teimo's Store
2. Click on batteries
3. Pay money to register
4. Open up the bag

**Mod Report:**
[MOP Bug Report - 2022-08-25_15-27.zip](https://github.com/Athlon007/MOP/files/9424602/MOP.Bug.Report.-.2022-08-25_15-27.zip)

**Additional context**
Not sure if reproducable as I don't know what happened

**Comment by Athlon007** [comment]
Confirmed, will be fixed in the next update.
