### ISSUE TITLE
[enhancement]compatibility with cd player mod

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#13]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]]

**Describe the solution you'd like** 
[A clear and concise description of what you want to happen.]the mop would work with this mod

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]...

**Additional context**
[Add any other context or screenshots about the feature request here.]...

there is an incompatibility issue with cd player mod, in this issue, the rack seems to work fine but the custom CDs will remain unloaded (even if it near the player at last saved spot) and eventually ending up falling out of the world (and the <<teleport to junkyard>> system seems to not work either) it will be a good idea to hear our favourite songs with this mod

**Comment by tonimark** [comment]
Sidenote!:each time you save the game the m.o.p will permanently damage the cd which means that even you remove the m.o.p the cd will remain unloaded

**Comment by Athlon007** [comment]
Fixed in 2.1.1
