### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by TheNakedRobbers** [Athlon007/MOP#131]
FIRST OFF! THANK YOU FOR MOP!! IT IS SO WONDERFUL! 

**Describe the bug**
[A clear and concise description of what the bug is.]
Cant provide much details as I did not experience any issue. MSC LOADER simple gave me a warning about an error and I followed the prompts in console hoping it would help. The game seems to freeze for a second after walker in the kitchen with a bag of food and supplies from the store. After the slight freeze there seemed to be no issue and I haven't had any since. 

**Steps to reproduce the behavior: to Reproduce simply **
1. Go to store buy some  batteries for flashlight and fuses, one case of beer. 
2. get your but home via your choice of transportation. 
3.  walk in the Kitchen turn left.
4.  turn the groceries bag upside down above the counter left of the sink. 
5. Spam F like your wife just left you, and..... 
6. it may or may not bug. 
7. I have no had the issue again. 

**Expected behavior**
[A clear and concise description of what you expected to happen.]
Slight Freeze. and console error warning via MSC LOADER. Maybe... I have only had the issue once
**Screenshots**

NA

**Mod Report:**

[MOP Bug Report - 2022-08-26_13-56.zip](https://github.com/Athlon007/MOP/files/9436794/MOP.Bug.Report.-.2022-08-26_13-56.zip)
[MOP_Logs.zip](https://github.com/Athlon007/MOP/files/9436796/MOP_Logs.zip)

**Comment by Athlon007** [comment]
Related to #129
