### ISSUE TITLE
satsuma leaning forward and engine slanted

### ISSUE THREAD

**Issue by gooeybop** [Athlon007/MOP#138]
**Describe the bug**
If you get too far from the Satsuma (going to town and coming back, or just going to the dock like in the screenshots), when you enter driving mode you lean forward, sometimes even turn upside down in the seat. The motor is also slanted to various degrees, it seems to get worse the farther you go.

**To Reproduce**
1. drive far enough away from the satsuma
2. come back
3. motor slanted and leaning forward when you sit down

**Expected behavior**
for the satsuma to be normal when you come back

**Screenshots**
![20220912122335_1](https://user-images.githubusercontent.com/113374598/189708514-5f0da083-6494-422f-ba12-be4f8c60b747.jpg)
![20220912122345_1](https://user-images.githubusercontent.com/113374598/189708517-cec09615-c220-43ba-a919-b6bef2a8dc63.jpg)
![20220912122347_1](https://user-images.githubusercontent.com/113374598/189708519-6c5ceb4e-dde0-4362-9d42-e2c943819a28.jpg)
![20220912122431_1](https://user-images.githubusercontent.com/113374598/189708521-2565a8e0-8179-4262-a4e8-3025e05dab7f.jpg)
![20220912122502_1](https://user-images.githubusercontent.com/113374598/189708524-2f7d1d89-777e-43cb-ab54-ce394d28f97b.jpg)
![20220912122510_1](https://user-images.githubusercontent.com/113374598/189708529-c67e2972-c055-4037-ba27-885c5c3b426b.jpg)

**Mod Report:**
[MOP Bug Report - 2022-09-12_12-25.zip](https://github.com/Athlon007/MOP/files/9550052/MOP.Bug.Report.-.2022-09-12_12-25.zip)
[README.txt](https://github.com/Athlon007/MOP/files/9550053/README.txt)

**Additional context**
[Add any other context about the problem here.]
it seems to worsen on farther trips

**Comment by Athlon007** [comment]
Hi there,
I can't reproduce your bug, but it seems like something's preventing MOP from downloading rule files. Is your firewall software, or your router blocking my webpage?

You can try downloading rule files pack and install them manually from here: http://athlon.kkmr.pl/mop/

**Comment by gooeybop** [comment]
hi, im *very* sorry for taking so long to respond. I downloaded all of the rule files and the issue still occurs, I dont believe that anything is blocking your website.
