### ISSUE TITLE
My Summer Car Bug

### ISSUE THREAD

**Issue by TUTUchikito** [Athlon007/MOP#142]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[MOP Bug Report - 2022-09-21_16-45.zip](https://github.com/Athlon007/MOP/files/9617770/MOP.Bug.Report.-.2022-09-21_16-45.zip)

[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Pirated game copies are NOT supported.
