### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by bigtyrone1234** [Athlon007/MOP#143]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

[MOP Bug Report - 2022-09-23_01-36.zip](https://github.com/Athlon007/MOP/files/9626297/MOP.Bug.Report.-.2022-09-23_01-36.zip)

everytime i boot up msc 
its says that the satsuma has not been fully loaded

**Comment by Athlon007** [comment]
Have you used MSCEditor to assemble the car?

**Comment by Athlon007** [comment]
Fixed in 3.9.1 Beta 1.
