### ISSUE TITLE
[A short bug description]

### ISSUE THREAD

**Issue by gooeybop** [Athlon007/MOP#144]
**Describe the bug**
hi, i was the one who made the bug report for the motor slanting once you get too far away, along with leaning far forward in the seat.
you still rotate *very* far forwards in the seat.

**To Reproduce**
[Steps to reproduce the behavior:
go far away from the suma
come back
you can now see the top 3 numbers on the odometer

**Expected behavior**
for this not to happen

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
in these, i drove past the bridge and back from fleetari's
![20220922123232_1](https://user-images.githubusercontent.com/113374598/191804068-b2dec911-a6e4-4297-b3b7-fb1de9f52ccf.jpg)
![20220922123738_1](https://user-images.githubusercontent.com/113374598/191804071-727a0254-c980-41d3-be95-7611b05ab662.jpg)

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-09-22_12-39.zip](https://github.com/Athlon007/MOP/files/9627808/MOP.Bug.Report.-.2022-09-22_12-39.zip)

**Additional context**
you lean farther forward than vanilla before you get too far away

**Comment by Athlon007** [comment]
I'm not exactly sure what's the problem.

**Comment by Athlon007** [comment]
Fixed in 3.9.1 Beta 1.
