### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by lowballasap** [Athlon007/MOP#145]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]
[MOP Bug Report - 2022-09-23_22-49.zip](https://github.com/Athlon007/MOP/files/9635188/MOP.Bug.Report.-.2022-09-23_22-49.zip)

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
I don't see any issues in the logs, and the issue has not been explained.
