### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Isutoku** [Athlon007/MOP#146]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[MOP Bug Report - 2022-09-26_18-12.zip](https://github.com/Athlon007/MOP/files/9647916/MOP.Bug.Report.-.2022-09-26_18-12.zip)

[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Pirated game copies are not supported.
