### ISSUE TITLE
When using the Mod ChaseCamera from nexus mods the game freezes and unfreezes alot making it almost unplayable.

### ISSUE THREAD

**Issue by CarGuy321** [Athlon007/MOP#147]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explai
[MOP Bug Report - 2022-09-28_09-15.zip](https://github.com/Athlon007/MOP/files/9666956/MOP.Bug.Report.-.2022-09-28_09-15.zip)
n your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
I'm unable to reproduce it. Is it just with the ChaseCam mod?

**Comment by CarGuy321** [comment]
Ya it’s only with the chase cam mod

**Comment by Athlon007** [comment]
I've tried on two computers, and I cannot reproduce it.

**Comment by CarGuy321** [comment]
honestly its all good not really that big of a problem, its probably more
of a thermal throttling issue anyways and it only happens when I am near
the house because all my cars are there, thanks anyways for trying.
