### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ricoryl1** [Athlon007/MOP#150]
**Describe the bug**
everytime when i load save, the "error has occured" shows

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
i was just playing and this thing comed up
**Screenshots**
![image](https://user-images.githubusercontent.com/115183161/194402517-ba8912a7-1ef4-44ad-a187-e16bfb92bd6c.png)

**Mod Report:**
[MOP Bug Report - 2022-10-06_21-30.zip](https://github.com/Athlon007/MOP/files/9728011/MOP.Bug.Report.-.2022-10-06_21-30.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Fixed in 3.9.2.
