### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by LeVaP45** [Athlon007/MOP#151]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[MOP Bug Report - 2022-10-07_20-29.zip](https://github.com/Athlon007/MOP/files/9734801/MOP.Bug.Report.-.2022-10-07_20-29.zip)

[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Related to #150
