### ISSUE TITLE
http://athlon.kkmr.pl/ is unreachable

### ISSUE THREAD

**Issue by ayesc9000** [Athlon007/MOP#153]
**Describe the bug**
The website which is used to download rules from is unreachable.

**To Reproduce**
1. Launch the game
2. MOP will display an error stating it cannot download rules

**Expected behavior**
MOP downloads rules and loads as expected

**Screenshots**
![Ping results](https://user-images.githubusercontent.com/29239155/194785269-dfdb950b-a3ab-4598-a136-eb710b61720f.png)
[Report details](https://check-host.net/check-report/d10da30k848)

**Mod Report:**
[MOP Bug Report - 2022-10-09_19-56.zip](https://github.com/Athlon007/MOP/files/9742795/MOP.Bug.Report.-.2022-10-09_19-56.zip)

**Additional context**
I confirmed that this issue was not my local network by using an external tool to ping the website. This seems to be a global issue.

**Comment by Athlon007** [comment]
Yeah I know, dumb me forgot to renew it in time 🙃

I’ve already repaid for it yesterday, but I think the website the domain is purchased from will only be reactivated today. Sorry!

**Comment by Athlon007** [comment]
Server is back online.
