### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by QuibbleTheBoss** [Athlon007/MOP#155]
[MOP Bug Report - 2022-10-13_22-07.zip](https://github.com/Athlon007/MOP/files/9779974/MOP.Bug.Report.-.2022-10-13_22-07.zip)
The access for the save file is restricted for some reason.

Makes me unable to save the game.

When I try to save It, It just says saving then the text disappears also the error message comes up when I return to menu.

**Comment by Athlon007** [comment]
Does it always, consistently happen to you?

**Comment by QuibbleTheBoss** [comment]
Yes

**Comment by Athlon007** [comment]
Could you please try the latest beta version? https://github.com/Athlon007/MOP/releases/tag/3.9.3-beta_2

**Comment by QuibbleTheBoss** [comment]
Still the same.

I just checked the folders and they are read only. However I can't untick them. MSC Editor gives off an error too.

**Comment by Athlon007** [comment]
In my experience, this is a bug in the MSC (well, not the MSC itself, but the save files framework it uses - EasySave2), where it sometimes leaves the save file in read-only state.

Try following these steps: https://www.partitionwizard.com/clone-disk/folder-keeps-reverting-to-read-only-win-10.html

**Comment by Athlon007** [comment]
OK, I have improved removing of read-only attribute from save file. It should work now :)
