### ISSUE TITLE
Parts catalog envelope not spawning and Teimo's advert pile disappearing

### ISSUE THREAD

**Issue by CarCrasher730** [Athlon007/MOP#157]
**Describe the bug**
When ever you order anything from the parts catalog the envelope doesnt spawn at first try you sort of have to order it many times and quickly click on the invisible envelope and let it go to get the envelope back to normal but when ever you go to Teimo's on friday to do the advert job and when you get near the apartments or off the highway (even if you beyond them) the pile disappears but if you have it still in hand and go back to teimos it will reappear.

**To Reproduce**
[Steps to reproduce the behavior:
1. Go to MOP Settings
2. Click on any modes except for safe mode
3. Then either order from the parts catalog or go to Teimo's at friday to do the advert job
4. Then see that neither the envelope or the advert pile spawns

**Expected behavior**
You have the envelope visible when you order from parts catalog and advert piles visible beyond the apartments or highway

**Screenshots**
When ordering parts from parts catalog at first try (https://imgur.com/a/eXub92y)
After multiple tries of ordering parts from parts catalog (https://imgur.com/a/2YpY8wO)
Teimo's advert pile when you aren't near or beyond the highway or the apartments (https://imgur.com/a/wXlTXjg)
Teimo's advert pile when you are near or beyond the highway or the apartments (https://imgur.com/a/oxWonJH)

**Mod Report:**
[MOP Bug Report - 2022-10-23_17-03.zip](https://github.com/Athlon007/MOP/files/9846793/MOP.Bug.Report.-.2022-10-23_17-03.zip)

**Comment by Athlon007** [comment]
Confirmed, will be fixed in the next update.

**Comment by Athlon007** [comment]
Fixed in the latest beta.

**Comment by CarCrasher730** [comment]
I see you fixed the envelope but what about the advert pile?

**Comment by Athlon007** [comment]
Oops, sorry! Missed that one 😅

I've included a fix for that now too.
