### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DikFuk69** [Athlon007/MOP#158]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
[MOP Bug Report - 2022-10-29_00-15.zip](https://github.com/Athlon007/MOP/files/9892979/MOP.Bug.Report.-.2022-10-29_00-15.zip)
On multiple occasions, parts of save file are saved, but others are not. On this save file, the engine, numerous parts, and the day are reverted essentially to a previous save. But new stuff (performance rad, gauges and others) are from new save. So I'd have to reinstall engine and all, plus I'm 2 in game days behind from where I was. Not the first time I've encountered the issue. Each time, makes the game feel unplayable. Great mod, until I started running into this issue.

**Comment by Athlon007** [comment]
Could you try installing the latest Beta release?
