### ISSUE TITLE
Mods that stop working or break when you are far + simple issue

### ISSUE THREAD

**Issue by Ikanaidexyz** [Athlon007/MOP#16]
The mods that have these problems are Donner's Turbocharger mod and Donner's ECU mod

I teleported with cheatbox far from the car and the turbocharger mod stopped working(i found that if you dont have the Vehicles check in Settings -> Advanced, the turbocharger mod will continue working fine but you have to sacrifice FPS. The ECU doesnt stop working or anything even if the Vehicles option is checked, but checked or without it still can cause it to break the car physics(it starts going forward when you reach some speed and doesnt stop, the wheels block and it continues to move) this happens even if you don't teleport or go far from the car, I thought that it was ECU's mod fault but after I deactivated the MOP mod it always worked fine, when I activated it again it broke several times. Maybe I'm wrong but everything I tried pointed to MOP making it work like that.
The "simple issue" is that when I go far and then go near the Satsuma again, the items inside the car or trunk are outside because of the vehicle spawning something like 1 or 2 meters from where it was before and it is pointing to another place, this makes the mod tedious to use when you want to leave things inside vehicles. (idk if there is a way to fix this in-game)

Game version is latest one as D14/M3/Y2020 and MSCLoader version is 1.1.6

PD: I love this mod, these are the problems I found so far

**Comment by Ikanaidexyz** [comment]
Sorry, i missed this. Let me know if you need something more

Modern Optimization Plugin
Version: 2.3.4
MSC Mod Loader Version: 1.1.6
Date and Time: 2020-03-14T20:37:00Z

=== MOP SETTINGS ===

ActiveDistance: 0
ActiveDistanceMultiplicationValue: 0.5
SafeMode: False
RemoveEmptyBeerBottles: False
SatsumaTogglePhysicsOnly: False
ToggleVehicles: True
ToggleItems: True
ToggleVehiclePhysicsOnly: False
IgnoreModVehicles: True
EnableFramerateLimiter: False
FramerateLimiter: 60

=== MODS ====

Backpack:
  ID: CarryMore
  Version: 1.4.3
  Author: Wampa842

CheatBox:
  ID: CheatBox
  Version: 1.1.6
  Author: Roman266

closepit:
  ID: closepit
  Version: 1.1.1
  Author: JIeCHuK

DonnerTechRacing ECUs:
  ID: DonnerTech_ECU_Mod
  Version: 1.1.4
  Author: DonnerPlays

Drug:
  ID: Drug
  Version: 1.0
  Author: Mihail

EasyHooksAPI:
  ID: EasyHooksAPI
  Version: 1.0
  Author: wolf_vx

EnableApartment:
  ID: EnableApartment
  Version: 1.7
  Author: Kunedo

License Plates:
  ID: LicensePlates
  Version: 1.0
  Author: MartyTheGamer

Shop Catalog - BETA:
  ID: ModsShop
  Version: 0.9.3
  Author: piotrulos

Msc Noclip:
  ID: MscNoclip
  Version: 1.3.1
  Author: haverdaden

Partition:
  ID: Partition
  Version: 1.0.2
  Author: Roman266

RailRoadCrossing:
  ID: RailRoadCrossing
  Version: 1.1.0
  Author: Wampa842

DonnerTechRacing Turbocharger:
  ID: SatsumaTurboCharger
  Version: 1.7.5
  Author: DonnerPlays

ShowBoltSize:
  ID: ShowBoltSize
  Version: 2.1
  Author: Lex (original by wolf_vx)

SixGearsReloaded:
  ID: SixGears
  Version: 1.0.3
  Author: Matt Smith, Wolf_vx

TrunkSnap:
  ID: TrunkSnap
  Version: 0.2
  Author: zamp

Wristwatch:
  ID: Wristwatch
  Version: 0.3
  Author: PigoenBB

**Comment by Athlon007** [comment]
Fixed in 2.4.
