### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Matyasq** [Athlon007/MOP#160]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
[MOP Bug Report - 2022-10-31_20-48.zip](https://github.com/Athlon007/MOP/files/9904633/MOP.Bug.Report.-.2022-10-31_20-48.zip)

4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.] Mod is dont boost a FPS

**Comment by Athlon007** [comment]
Sorry, but you're using a pirated and outdated version of the game. Pirated copies are not supported.
