### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DikFuk69** [Athlon007/MOP#163]
**Describe the bug**
[A clear and concise description of what the bug is.]
Having the problem still with save file, where some stuff gets saved, but other stuff seems left from a previous save. And this time the wheels from the mansion even lost the tires, so they are bare wheels. Seems money, player position, and parts attached to car seem most likely to be from previous save (in this case from start of game. Started a new game after latest release of MOP.), while other things stay current, like wheels, beer case, etc. being where I left them when I saved.
**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
Only other mod being used is MSC Save Backup Manager.
[MOP Bug Report - 2022-11-04_20-19.zip](https://github.com/Athlon007/MOP/files/9942573/MOP.Bug.Report.-.2022-11-04_20-19.zip)

**Comment by Athlon007** [comment]
Could you please check if the save file (specifically, the defaultES2Save.txt) is read-only?

**Comment by DikFuk69** [comment]
Is not read-only. I did disable MOP at one point and still ran into a
slight save discrepancy. Trying to isolate and see if it is the backup
manager causing the issue.

**Comment by Athlon007** [comment]
I'm really sorry, but I really can't replicate the issue, nor I can't find where in MOP's code it might happen.

**Comment by DikFuk69** [comment]
No worries brother! I'm gonna assume it's the backup manager and just stop
using that and reenable MOP and see how i fair. Which is good news. Much
rather be able to use MOP again! Thank you.
