### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Lazikbro12** [Athlon007/MOP#165]
In game my urine etc is not transparent anymore
![My Summer Car 13 11 2022 19_39_56](https://user-images.githubusercontent.com/96190955/201538607-8afb52ef-5d9a-47a8-b6f1-2faa7a1308d1.png)

**Comment by Athlon007** [comment]
I'm sorry, but from what I remember, purple background of the HUD is an indicator of pirated copy of the game. Pirated game copies are NOT supported.
