### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by usuusf** [Athlon007/MOP#167]
[MOP Bug Report - 2022-11-22_16-32.zip](https://github.com/Athlon007/MOP/files/10068856/MOP.Bug.Report.-.2022-11-22_16-32.zip)
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by usuusf** [comment]
[MOP Bug Report - 2022-11-22_16-32.zip](https://github.com/Athlon007/MOP/files/10068861/MOP.Bug.Report.-.2022-11-22_16-32.zip)

**Comment by Athlon007** [comment]
Sorry, but pirated game copies are not supported.
