### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Jeyroo1** [Athlon007/MOP#168]
**Describe the bug**
[MOP Bug Report - 2022-11-25_20-41.zip](https://github.com/Athlon007/MOP/files/10092877/MOP.Bug.Report.-.2022-11-25_20-41.zip)

[A clear and concise description of what the bug is.]
the mop mod is so laggy and if i open my game the MOP File will start to crash sometimes my laptop starts to lag when i open the summer car my Laptop have a high specs
**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Sorry, but pirated game copies are not supported.
