### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ikeman2003** [Athlon007/MOP#169]
**Describe the bug**
When MOPs is enabled and you go to use the jack it messes with the physics and simply moves the car like it has no weight I have even had it shoot the car body up and cause it to float.

**To Reproduce**
1 start a game
2 use the floor jack on the car body
3 watch it move cuz physics

**Expected behavior**
The car is supposed to have weight so the jack can slide under the car

**Screenshots**
I have 2 clips since i was streaming the game when this was discoved
https://clips.twitch.tv/AgreeableCogentSpiderSpicyBoy-_qFQ0toW1hE1wiIx
https://clips.twitch.tv/BreakableBlushingFlamingoTBTacoLeft-7lLyZO9StQBdxuXJ

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
[MOP Bug Report - 2022-11-25_19-13.zip](https://github.com/Athlon007/MOP/files/10095369/MOP.Bug.Report.-.2022-11-25_19-13.zip)

**Comment by Athlon007** [comment]
Will be fixed in the upcoming MOP update.
