### ISSUE TITLE
Add support for following mods...

### ISSUE THREAD

**Issue by bunchOpaper** [Athlon007/MOP#17]
Not much to say in here, I think the supported mods list should be improved. Here is a few suggestions for good mods to add:

Casette Tapes:
https://www.racedepartment.com/downloads/cassette-tapes.17698/

Gifu Addon
https://www.nexusmods.com/mysummercar/mods/48

Turbo Hayosiko
https://www.racedepartment.com/downloads/hayosiko-turbo.25493/

Ruscko Restoration Project
https://www.nexusmods.com/mysummercar/mods/61

Mokia Townsman
https://www.nexusmods.com/mysummercar/mods/66

(I have not tested these mods)
Not sure if you can add all of these, but if you can add support for at least some, I will be happy.

**Comment by bunchOpaper** [comment]
Not sure if I actually have to test the mods myself, please correct me if I misunderstood

**Comment by Athlon007** [comment]
All of these mods work with MOP already...
