### ISSUE TITLE
Well i dont know what the bug was 

### ISSUE THREAD

**Issue by Ognjen1127** [Athlon007/MOP#170]
The console told me that the bug was SATSUMA_TOGGLE_ELEMENTS_ERROR so i just followed to here to file this bug
[MOP Bug Report - 2022-11-30_19-55.zip](https://github.com/Athlon007/MOP/files/10126471/MOP.Bug.Report.-.2022-11-30_19-55.zip)

**Comment by Athlon007** [comment]
MOP does not support  pirated game copies.
