### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ibocan22** [Athlon007/MOP#172]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
[MOP Bug Report - 2022-12-04_21-16.zip](https://github.com/Athlon007/MOP/files/10149190/MOP.Bug.Report.-.2022-12-04_21-16.zip)

**Comment by ibocan22** [comment]
Im just playing MSC(My Summer Car) and idk im have a error from my mod im dont use steam please fix.

**Comment by Athlon007** [comment]
MOP does not support pirated game copies.
