### ISSUE TITLE
After saving and reloading my game completely suddenly broke

### ISSUE THREAD

**Issue by TheRealDadbeard** [Athlon007/MOP#173]
**Describe the bug**
My console opens with multiple errors and UI mover doesnt move every element. I cooked like 12 sausages before saving and they are all gone too. Minimap just opens now on every launch and the game feels broken.

**To Reproduce**
I have none. It just happened.

**Expected behavior**
Nothing breaks

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-12-06_01-32.zip](https://github.com/Athlon007/MOP/files/10159347/MOP.Bug.Report.-.2022-12-06_01-32.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Fixed in 3.10.3.
