### ISSUE TITLE
Bug - MOP seems to turn itself off

### ISSUE THREAD

**Issue by Chong-McBong** [Athlon007/MOP#18]
**Describe the bug**
The 2.4 and 2.41 versions of MOP disable themself after playing for a while, and doesn't seem to turn back on.

even after restarting the game, MOP appears to be working and up to date, but shows nothing in the console loading/unloading, also beer bottles don't dissapear any more. 

i reverted back to 2.3.4 and that runs fine.

runing the latest experimental version of MSC, no other mods

if you need more info, let me know :)

👍

**Comment by Athlon007** [comment]
Could you provide me with output_log? You can find it in My Summer Car folder -> mysummercar_Data -> output_log.txt

**Comment by Chong-McBong** [comment]
no problemo, heres the log:

[output_log.txt](https://github.com/Athlon007/MOP/files/4346141/output_log.txt)

**Comment by Athlon007** [comment]
It should be fixed right now, try out the 2.4.2.

**Comment by Chong-McBong** [comment]
many thanks :)

**Comment by Athlon007** [comment]
Thank YOU! Finally someone who provided sufficient data 😁

**Comment by Chong-McBong** [comment]
hi again, i had the same issue with the new version of MOP last night. it appeared to be running, but showed nothing in the console, and appeared twice in the mod loader menu when i reloaded the game. it also said there was an update available, even though i was on the latest version.

it ran fine for a few hours, then somehow turned itself off and failed to restart at a save/load
[output_log.txt](https://github.com/Athlon007/MOP/files/4362017/output_log.txt)


i'm not sure how much use the log is, as i played on after it failed, and then swapped to MOP 2.4.2 for a while (with no result)
