### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Hadex1** [Athlon007/MOP#188]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]
[MOP Bug Report - 2022-12-11_13-33.zip](https://github.com/Athlon007/MOP/files/10201933/MOP.Bug.Report.-.2022-12-11_13-33.zip)

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Please update to MOP 3.10.4 first, and try again.

**Comment by Hadex1** [comment]
sure one second

**Comment by Hadex1** [comment]
thanks brother
