### ISSUE TITLE
haysiko off-road mod is broken after last update 

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#19]
**Describe the bug**
[A clear and concise description of what the bug is.]
the  haysiko off-road mod gets disabled after a while
**To Reproduce**
[Steps to reproduce the behavior:
1. install off-road haysiko
2. load the game
3. see the error (appears after a while)
4. 

**Expected behavior**
the mod would load

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** Experimental last update:8 of April 2020

**Mod Report:**
 [Go into mod settings and click "Generate mod report", and paste the content here]
[MOP_REPORT.txt](https://github.com/Athlon007/MOP/files/4460233/MOP_REPORT.txt)

**Additional context**
some very loud gearbox slip sounds may be heard at first, but later on, they will disappear

**Comment by Athlon007** [comment]
Fixed.

You have to update rule files. Start MSC, go into Mods Settings -> MOP Settings -> Scroll Down -> Click "Force Update".
