### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by paul2312** [Athlon007/MOP#202]
**Describe the bug**
The bug is so annoying that you lose the desire to play because you can't play well without Mop.

**To Reproduce**
[Steps to reproduce the behavior:
1. Go into your Satsuma
2. Put an item on the car floor 
3. See what happens

**Expected behavior**
The Satsuma will fly away and kill you. 

**Mod Report:**
[MOP Bug Report - 2022-12-23_01-42.zip](https://github.com/Athlon007/MOP/files/10291176/MOP.Bug.Report.-.2022-12-23_01-42.zip)

**Additional context**
Satsuma will fly away or respawn at home destroyed. If you are in the car it will kill you

**Comment by Athlon007** [comment]
I can't reproduce it. Which items did you try putting on the car's floor?

**Comment by paul2312** [comment]
> I can't reproduce it. Which items did you try putting on the car's floor?

It happened with a Beer crate or the Flashlight

**Comment by paul2312** [comment]
> I can't reproduce it. Which items did you try putting on the car's floor?

I tested it once again. <it happens if you try to lean to the right.
