### ISSUE TITLE
Car ended up on the roof

### ISSUE THREAD

**Issue by Krutonium** [Athlon007/MOP#21]
**Describe the bug**
My Satsuma ended up on the roof.

**To Reproduce**
I have no idea. But this was the only mod at the time.

**Expected behavior**
My car, ideally, should not be on the roof.

**Screenshots**
https://clips.twitch.tv/ClumsyBlindingSowEagleEye

**Game Version:** [e.g. 15.11.2019/Experimental]
22/04/2020 Experimental

**Mod Report:**
Will do when sitting at correct PC

**Additional context**
Not sure what to say, aside from uh, I guess this is going to be extremely hard to reproduce, but this is more a "idk how this happened but it did" thing.

**Comment by Athlon007** [comment]
May be fixed in [2.7 Dev 3](https://github.com/Athlon007/MOP/releases/tag/2.7-dev.3). Needs testing tho...

**Comment by Krutonium** [comment]
So far so good, I'm not seeing it happen.
