### ISSUE TITLE
Don't check internet connection when auto updating is turned off

### ISSUE THREAD

**Issue by Kattus** [Athlon007/MOP#22]
**Describe the bug**
Even with "Rules Auto Update" turned off, MOP will tell me to "Check your Internet connection." every single time I start the game.

**To Reproduce**
1. Disconnect from internet or run in Linux via Proton (my case)
2. Disable "Rules Auto Update"
3. Watch MOP tell you "Error: [MOP] Connection error. Check your Internet connection."

**Expected behavior**
Don't check for an internet connection when the one and only feature requiring internet is turned off.

**Screenshots**
![](https://i.imgur.com/xDXo50c.pngl)

**Game Version:**
Experimental

**Mod Report:**
https://gist.github.com/Kattus/a0c2bc2015d68bad2eb1dc0fc5d37c7a

**Additional context**
I'm running this mod via Steam Proton to play the game on Linux, the mod works great other than this tiny annoyance :)

**Comment by Athlon007** [comment]
Ok, will be fixed in next development version.

**Comment by Athlon007** [comment]
Fixed in 2.7 Development 3.
