### ISSUE TITLE
bug with MOP on

### ISSUE THREAD

**Issue by Fontinhagamer** [Athlon007/MOP#28]
**Describe the bug**
the bug consists of when spawning, for example in the bathroom of the house, I can't move just the camera and squat, it's like I don't have buttons assigned to the player's functions on the floor.
I already turned off the Mop, and with it turned off most of the time when spawna I can walk, and some is frozen, but then it seems that the player falls off the map and spawna for example on the roof of the house, but can walk, with the MOP on this does not happen, the player is frozen, I have restarted the pc, the game, the save, and it remains the same. The mod is very good but now this problem is happening.
At the beginning when I started using it none of this happened but now 3 days ago I started doing this.
This started to happen in the normal version of the game, today I switched to the beta version and it remains the same

**To Reproduce**
[Steps to reproduce the behavior:
1. active MOP
2. continue to game (inside save)
3. try to walk
4. holding down WASD even with the door open and unable to move (walking) is the problem
try with the mod turned off to see if it is a bug in the mod or the game itself

**Expected behavior**
I hope the spawn is not able to move, this being the problem

**Screenshots**
screenshots fail to show the problem

**Game Version:** [Experimental 64bit testing branch]

**Mod Report:**
[MOP_REPORT.txt](https://github.com/Athlon007/MOP/files/4869883/MOP_REPORT.txt)

**Additional context**
[MOP_LOG.txt](https://github.com/Athlon007/MOP/files/4869885/MOP_LOG.txt)
[output_log.txt](https://github.com/Athlon007/MOP/files/4869886/output_log.txt)

I really liked the mod, I think it is a job well done and I would like to see this probable bug solved.
I await response or solution

**Comment by Athlon007** [comment]
To me it looks like your copy of the game is broken. Try reinstalling the game.

**Comment by Athlon007** [comment]
Closed due to lack any further info.
