### ISSUE TITLE
ATHLON007 DOESN'T UPDATE THIS MOD ANYMORE! SEE THE DETAILS IN THIS ISSUE!

### ISSUE THREAD

**Issue by hidesna** [Athlon007/MOP#29]
Hi everyone, I'm very sad to say this, but **Athlon is tired of updating this mod. He wrote about it [here](https://www.racedepartment.com/downloads/mop-modern-optimization-plugin.30073/)**. Quote:"_Sorry, I'm too tired of working on MOP and this game, listening to little kids expecting to get AAA quality software for free. I already spent too much time working on MOP_."
_________________________________________________________________________________________________________________________________________

You don't have to read this, this is an old problem that will never be solved :(

**Describe the bug**
CD falling out of the world when I insert it in CD player.

**To Reproduce**
1. Create CD
2. Buy CD in Teimo's shop
3. Insert CD in player
4. See strange things :D 

**Expected behavior**
I was expecting to see the disk insert into the player.

**Screenshots**
![20200720120822_1](https://user-images.githubusercontent.com/68538321/87920661-2eec0380-ca82-11ea-93a0-057547e7426e.jpg)
![20200720120831_1](https://user-images.githubusercontent.com/68538321/87920667-30b5c700-ca82-11ea-8da9-e823e8383fb1.jpg)
![20200720120837_1](https://user-images.githubusercontent.com/68538321/87920668-30b5c700-ca82-11ea-9e70-e0fefbd042d5.jpg)

**Game Version:** Last version in steam(Not experimental)

**Mod Report:**
Modern Optimization Plugin
Version: 2.12.2
MSC Mod Loader Version: 1.1.7
Date and Time: 2020-07-20T12:17:19Z
Windows 10 (10.0.14393) 64bit 

=== MOP SETTINGS ===

ActiveDistance: 1
ActiveDistanceMultiplicationValue: 1
SafeMode: False
RemoveEmptyBeerBottles: True
ToggleVehiclePhysicsOnly: False
IgnoreModVehicles: False
EnableFramerateLimiter: True
FramerateLimiter: 45
EnableShadowAdjusting: False
KeepRunningInBackground: True
DynamicDrawDistance: False
ShadowDistance: 200
RulesAutoUpdate: True
RulesAutoUpdateFrequency: 2
CustomRuleFile: False

CheckSteam: True 
ExperimentalBranch: False

=== MODS ===

CDPlayer Enhanced:
  ID: CDPlayer
  Version: 1.3.3
  Author: Piotrulos

ChaseCamera:
  ID: ChaseCamera
  Version: 1.4.1
  Author: cbethax

CheatBox:
  ID: CheatBox
  Version: 1.1.6
  Author: Roman266

DonnerTechRacing ECUs:
  ID: DonnerTech_ECU_Mod
  Version: 1.3.1
  Author: DonnerPlays

GrabAnything:
  ID: GrabAnything
  Version: 1.3.0
  Author: haverdaden

Lifter:
  ID: Lifter
  Version: 8.6
  Author: Kunedo

Shop Catalog - BETA:
  ID: ModsShop
  Version: 0.9.3
  Author: piotrulos

Msc Noclip:
  ID: MscNoclip
  Version: 1.3.1
  Author: haverdaden

NewJob:
  ID: NewJob
  Version: 0.7
  Author: Kunedo

Rent Apartment:
  ID: PsychovanzRentApartment
  Version: 1.0.4
  Author: psychovanz

DonnerTechRacing Turbocharger:
  ID: SatsumaTurboCharger
  Version: 2.1.6
  Author: DonnerPlays

ShowBoltSize:
  ID: ShowBoltSize
  Version: 2.1
  Author: Lex (original by wolf_vx)

ShowWear:
  ID: ShowWear
  Version: 1.2
  Author: haverdaden (updated by Simon)

=== RULE FILES ===

CDPlayer.mopconfig
DonnerTech_ECU_Mod.mopconfig
PsychovanzRentApartment.mopconfig
SatsumaTurboCharger.mopconfig

**Additional context**
-

**Comment by Athlon007** [comment]
Fixed in 3.0.
