### ISSUE TITLE
[suggestion] add compatibility with off-road haysiko 

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#3]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] mod gets disabled
compatibility  
**Describe the solution you'd like**
the mod would be still fuctional

**Describe alternatives you've considered**
i would like to have compatibility because when the mod disables haysiko the off-road haysiko gets disabled for throwing too many errors
**Additional context**

**Comment by Athlon007** [comment]
Added in Beta 1.5
