### ISSUE TITLE
[GIFU] hand throttle won't work and air pressure resets back 

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#31]
**Describe the bug**
[A clear and concise description of what the bug is.]
after the mop disables and re-enables gifu the hand throttle won't work also the pressure will reset back
**To Reproduce**
[Steps to reproduce the behavior:
1. Go away from the gifu truck , make sure pressure is 0 
2. Come back
3. See error check the hand throttle and pressure

**Expected behavior**
[A clear and concise description of what you expected to happen.]
the hand throttle would work and the air pressure would save between disabling and enabling 
**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 15.11.2019/Experimental]
experimental branch 16
**Mod Report:**
 [Go into mod settings and click "Generate mod report", and paste the content here]
[MOP_REPORT.txt](https://github.com/Athlon007/MOP/files/5045286/MOP_REPORT.txt)

**Additional context**
[Add any other context about the problem here.]there are no additional gifu mods installed except the cassette tapes which modifies the radio

**Comment by Athlon007** [comment]
Fixed in 3.0.
