### ISSUE TITLE
satsuma somehow broken...

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#32]
here's what happened... 
PRE-EXISTING ISSUE: somehow all the oil was drained from satsuma and I had to refill it manually 
0.5)the tire racks mod racks were teleported all to the kitchen table and painted black
1) I picked fish from the new inventory mod,
2)I started the satsuma and drove to grandma 
3)I teleported back home to check where the fish were... 
3.5) I use fast travel mod to go to junkyard just in case the fish fell through the world
4)with no clue I teleported back to grandma 
5)THE BIG ISSUE, donnertech  turbocharger mod (with the 2 types of turbo installed) was installed was incompatible (I had stock carburettor) the whole oil level suddenly emptied despite the screws (on oil pan) were tightened) also, the oil pouring sound was being listened to near the engine bay
side note: the roof rack was installed and also was initially found on the house rooftop instead of uncle's house back
REPORT FILE:[MOP Bug Report - 2021-02-24_23-51.zip](https://github.com/Athlon007/MOP/files/6039071/MOP.Bug.Report.-.2021-02-24_23-51.zip)
 screenshot of satsuma's messed engine bay:
![20210224234658_1](https://user-images.githubusercontent.com/17166550/109071739-c9898080-76fc-11eb-891a-bf928e82fed8.jpg)
![20210225000236_1](https://user-images.githubusercontent.com/17166550/109071744-cabaad80-76fc-11eb-90ef-c704ee764ecd.jpg)

**Comment by Athlon007** [comment]
Sorry, but there's way too many mods involved, possibly interfering with MOP or others. I can't possibly debug this.
