### ISSUE TITLE
MOP does not work 

### ISSUE THREAD

**Issue by Lodmsc** [Athlon007/MOP#38]
**Describe the bug**
MOP cannot start

**To Reproduce**
load save

**Screenshots**
![image](https://user-images.githubusercontent.com/93322254/139243323-47c1136d-47c3-400d-90a3-55f8902e968f.png)

**Game Version**
most likely, v 20.08.2021

**Mod Report:**
Modern Optimization Plugin
Version: 3.3.5
MSC Mod Loader Pro Version: 1.1.0
Date and Time: 2021-10-28T15:05:04Z
Windows 7 Service Pack 1 (6.1.7601) 64bit
Session ID: f4a52666-9345-4e4f-aa5b-99e965734ec7
Game Restarts: 2
Game resolution: 1024x768
Screen resolution: 1024x768
Session Time: 0 Hours 0 Minutes 57 Seconds

=== MOP SETTINGS ===

ActiveDistance: 1
ActiveDistanceMultiplier: 1
PerformanceMode: Balanced
FramerateLimiter: 210
ShadowAdjust: False
ShadowDistance: 100
RunInBackground: True
DynamicDrawDistance: True
RulesAutoUpdate: True
VerifyRules: True
RulesAutoUpdateFrequency: 2
RuledDeleteAutomatically: False
DestroyEmptyBottles: True
DisableEmptyItems: False
ToggleVehiclePhysicsOnly: False
IgnoreModVehicles: False
CustomRuleFile: False

=== GAME DATA ===

PlayerPosition: (-8.2, -0.3, 11.6)
PlayerHasHayosikoKey: False
IsPlayerInCar: False
IsPlayerInSatsuma: False
DrawDistance: 1571.305
CanTriggerStatus: Found (JOBS/HouseDrunk/BeerCampOld/BeerCamp/KiljuBuyer/CanTrigger)
IsTrailerAttached: False
AverageFramerate: 46 FPS

=== MODS (14) ===

Backpack:
  ID: CarryMore
  Version: 1.4.3
  Author: Wampa842
  Enabled: True
  

CheatBox:
  ID: CheatBox
  Version: 1.1.6
  Author: Roman266
  Enabled: False
  

ExtraTranslate:
  ID: ExtraTranslate
  Version: 1.1.2
  Author: Roman266
  Enabled: True
  

FSMO:
  ID: FSMO
  Version: 1.1.0
  Author: Horsey4
  Enabled: False
  

GrabAnything:
  ID: GrabAnything
  Version: 1.4.3
  Author: haverdaden
  Enabled: False
  

LanguageFramework:
  ID: LanguageFramework
  Version: 1.2.3C
  Author: jinnin0105
  Enabled: True
  

LFTTFix:
  ID: LFTTFix
  Version: 1.0.3
  Author: Roman266
  Enabled: True
  

Light switch markers:
  ID: LightSwitchMarkers
  Version: 1.0.0
  Author: Wampa842
  Enabled: True
  

Msc Noclip:
  ID: MscNoclip
  Version: 1.2.0
  Author: haverdaden
  Enabled: False
  

New Fonts:
  ID: NewFonts
  Version: 1.0.0
  Author: Roman266
  Enabled: True
  

Pause:
  ID: Pause
  Version: 1.0.5
  Author: Roman266(fix by mads232)
  Enabled: False
  

Satsuma Vin Plate:
  ID: SatsumaVinPlate
  Version: 2.01
  Author: komeo
  Enabled: False
  

ShowBoltSize:
  ID: ShowBoltSize
  Version: 2.1
  Author: Lex (original by wolf_vx)
  Enabled: True
  

=== RULE FILES ===

No rule files loaded!

**Additional context**
I just load my save and the mod refuses to work. I've tried different versions of Mod Loader Pro and MOP, tried booting without other mods, tried to start new game, but nothing changes.

https://drive.google.com/file/d/17Xze2crGdN-Du3-B26ld3eXrSNODRn00/view?usp=sharing

**Comment by Athlon007** [comment]
The latest crash log has not been included in the bug report. Please upload the report from 28th October 2021.

**Comment by Athlon007** [comment]
As there is no further update, I consider the issue to be solved.
