### ISSUE TITLE
DX11 support?

### ISSUE THREAD

**Issue by panos4512** [Athlon007/MOP#39]
As the title says will mop support dx11?
To be honest i tried the dx11 experimental update for the first time two days after it came out, it seems to be working well enough without major issues and also a lot better than msc without dx11.
So i would like to see mop work with dx11 and compare it with the dx11 on or off!
I think it will be really cool. 
What do you think?

**Comment by Athlon007** [comment]
There is absolutely no reason why MOP should not work with DX11 (in fact, [on MOP Wiki there is a recommendation to force the DX11 on](http://athlon.kkmr.pl/mop/wiki/#/faq?id=how-can-i-improve-the-framerate-even-more)). 

Closing.

**Comment by panos4512** [comment]
Ok my bad, i only tried dx11 once without the mod cause i thought it wouldn't support it and also i didn't get the full experience from it but thanks for the info.
