### ISSUE TITLE
satsuma got texture glitched and is undrivable

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#4]
**Describe the bug**
A clear and concise description of what the bug is
satsuma is texture glitched and undrivable (gt interior, chrome grill, fuel tank cap and gt budget)

**To Reproduce**
1. install this mod above (optional) (not sure if mod causes the problem)
2. go on far distance so the M.O.P can disable the satsuma 
3. return back

**Expected behavior**
the satsuma would look normal and be drivable
**Screenshots**
![20200106202642_1](https://user-images.githubusercontent.com/17166550/71839570-26267800-30c4-11ea-9e96-11a279da67a5.jpg)

**Game Version:** [e.g. 15.11.2019/Experimental]
latest release (23.12.2019)
**Mod Report:**
 [Go into mod settings and click "Generate mod report", and paste the content here]
[MOP_REPORT.txt](https://github.com/Athlon007/MOP/files/4027372/MOP_REPORT.txt)

**Additional context**
the gt grille got invisible (chrome grille mod) the tachymeter disappeared too (completely stock)
also the wheel got missing from dvd radio and i can't longer turn the radio on (permanent issue)

**Comment by Athlon007** [comment]
I'm 99% sure that it's caused by some mod (probably one of the GT mods).

**Comment by tonimark** [comment]
the updates are done so far fixed satsuma's problem (with an alternative solution satsuma, toggle physics only)
