### ISSUE TITLE
Bug Report about a new minor incompatibility with the ColorfulGauges3 mod.

### ISSUE THREAD

**Issue by Satsumarider** [Athlon007/MOP#40]
**Describe the bug**
ColorfulGauges3 Mod is partly broken, the speedometer's and tachometer's (Small RPM Gauge) needles no longer light up, however the numbers and the other gauges still do. When MOP is disabled, ColorfulGauges3 works as intended.

**To Reproduce**
[Steps to reproduce the behaviour:
1. Go to the 'Backyard' of the house.
2. Start the yellow Satsuma, the gauge lights should already be on, but the speedometer and tachometer needles will not be lit up.

**Expected behaviour**
I'd have expected the gauge lights to work as intended, just like they were before MOP Update 3.3.9.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** Most recent update as of 28th of December 2021, with Mod Loader Pro 1.1.1
(In the properties of the .exe file for the game, the game is File version 5.0.0.39095, and Product version 5.0.0.6002871)

**Mod Report:**
[MOP Bug Report - 2021-12-28_00-28.zip](https://github.com/Athlon007/MOP/files/7782129/MOP.Bug.Report.-.2021-12-28_00-28.zip)

**Additional context**
ColorfulGauges3 stopped functioning as intended after the release of MOP 3.3.9.
In the save, the Satsuma is located in the back yard, next to the patio chair and table.

**Comment by Athlon007** [comment]
The issue has been found and fixed in version 3.3.10.

Thanks for reporting it.
