### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by zbloo3** [Athlon007/MOP#41]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 15.11.2019/Experimental]

**Mod Report:**
[MOP Bug Report - 2021-12-31_13-53.zip](https://github.com/Athlon007/MOP/files/7796182/MOP.Bug.Report.-.2021-12-31_13-53.zip)

 [Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Sorry, but as you have a pirated copy of MSC, MOP may not work with your copy of the game.
