### ISSUE TITLE
Items disappear after buying

### ISSUE THREAD

**Issue by ChangeDev** [Athlon007/MOP#42]
**Describe the bug**
Items disappearing after buying them in shop(s). Not sure if it happens at others, haven't tested, but as far as I've tested it does happen at Teimo's.

**To Reproduce**
[Steps to reproduce the behavior:
1. Go to Teimo's Store
2. Buy ANY item.
3. Pay and see the items disappear.

**Expected behavior**
The item spawns in normally on the table without disappearing and you can grab it.

**Screenshots**
GIF: https://gyazo.com/3920e8dc6a1f242ac315934c44f99dc9

**Game Version:** [e.g. 15.11.2019/Experimental]
Using experimental, happened today after updating (03.01.2022)

**Mod Report:**
For some reason I couldn't press it even when I restarted the game, does this:
https://gyazo.com/1df7cb8652007669068be561a574e029

**Additional context**
Nothing, I just need my damn car battery!

**Comment by ChangeDev** [comment]
Also using MSCLoader, not the Pro thing.

**Comment by ChangeDev** [comment]
Also adding that the game is not pirated, downloaded and bought from Steam.

**Comment by Athlon007** [comment]
The issue has been found and has been fixed in update 3.4.2.

Thanks for reporting it!
