### ISSUE TITLE
mod wont load propperly

### ISSUE THREAD

**Issue by mrawesome7123** [Athlon007/MOP#44]
when i press continue to load into my savegame the mod loads and immediately throws an error, it does this a few more times then enables safe mode

idk if it will be the same for you but
1.press continue game on your savegame
2.mod does the thing i described in the first bit

**Expected behavior**
i'll keep it brief, i expected the mod to function, like at all,

**Screenshots**
![20220104175014_1](https://user-images.githubusercontent.com/55339185/148139348-b48d58e5-6908-4622-8371-97e6e1219cb8.jpg)

24.10.2021

**Mod Report:**
Modern Optimization Plugin
Version: 3.4.2
MSC Mod Loader Version: 1.2.4
Date and Time: 2022-01-04T17:49:44Z
Windows 11 (10.0.22000) 64bit
Session ID: 8b1653f2-73fc-4680-8381-078a3f431d0a
Game Restarts: 1
Game resolution: 1920x1080
Screen resolution: 1920x1080
Session Time: 0 Hours 0 Minutes 1 Seconds

=== MOP SETTINGS ===

ActiveDistance: 1
ActiveDistanceMultiplier: 1
PerformanceMode: Safe
LimitFramerate: False
FramerateLimiter: 60
ShadowDistance: 200
RunInBackground: True
DynamicDrawDistance: False
RulesAutoUpdate: True
VerifyRules: False
RulesAutoUpdateFrequency: 2
RuledDeleteAutomatically: False
DestroyEmptyBottles: False
DisableEmptyItems: False
ToggleVehiclePhysicsOnly: False
IgnoreModVehicles: False
CustomRuleFile: False

=== GAME DATA ===

PlayerPosition: (-1464.8, 4.1, 1140.8)
PlayerHasHayosikoKey: True
IsPlayerInCar: False
IsPlayerInSatsuma: False
DrawDistance: 3000
CanTriggerStatus: Found (JOBS/HouseDrunkNew/BeerCampNew/BeerCamp/KiljuBuyer/CanTrigger)
IsTrailerAttached: False

=== MESSAGES ===

17:49:24: Server Status: Online
17:49:24: Checking for new mods...
17:49:24: No updates required.
17:49:24: Updating rules completed.
17:49:24: No rule files found.
17:49:24: MOP hasn't found any problems with your save :)
17:49:24: [SYSTEM] MOP 3.4.2 initialized!
17:49:43: Loading MOP...
17:49:43: Found 164 bolts.
17:49:43: Vehicles initialized
17:49:43: World objects (1) loaded
17:49:43: [WARNING] An error has occured. The log file has been saved folder into:

D:/SteamLibrary/steamapps/common/My Summer Car//MOP_Logs/MOP_Crash_2022-01-04-17-49.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
17:49:43: [WARNING] An error has occured. The log file has been saved folder into:

D:/SteamLibrary/steamapps/common/My Summer Car//MOP_Logs/MOP_Crash_2022-01-04-17-49_0.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
17:49:44: Finished applying fixes
17:49:44: [WARNING] An error has occured. The log file has been saved folder into:

D:/SteamLibrary/steamapps/common/My Summer Car//MOP_Logs/MOP_Crash_2022-01-04-17-49_1.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
17:49:44: Satsuma triggers loaded
17:49:44: Jokke's furnitures found and loaded
17:49:44: Items class initialized

=== MODS (2) ===

Console:
  ID: MSCLoader_Console
  Version: 1.2.4
  Author: piotrulos

Settings (Main):
  ID: MSCLoader_Settings
  Version: 1.2.4
  Author: piotrulos

No other mods found!

=== RULE FILES ===

No rule files loaded!

=== ERROR ===

// Uh-oh!

SAVE_HOOK_ERROR

Object reference not set to an instance of an object
  at MOP.Hypervisor.HookPreSaveGame () [0x00000] in <filename unknown>:0 
Target Site: Void HookPreSaveGame()

**Comment by Athlon007** [comment]
This might be your save file specific issue.

Please go into MOP settings and use "I Found a Bug" button and **INCLUDE** the safe file.

**Comment by Athlon007** [comment]
Due to the lack of information about the problem, the issue is closed.
