### ISSUE TITLE
My mop wont load When inside the game. 

### ISSUE THREAD

**Issue by Estiloooo38A** [Athlon007/MOP#46]
[MOP Bug Report - 2022-01-14_22-36.zip](https://github.com/Athlon007/MOP/files/7871587/MOP.Bug.Report.-.2022-01-14_22-36.zip)

Game Version : fluid level update
How the bug could happend? When I loaded the game the commands says mop failed to load in time
![putanginam](https://user-images.githubusercontent.com/97748742/149611902-da7f55fc-b8d3-4571-9b9e-26c72a135249.PNG)

**Comment by Estiloooo38A** [comment]
so how to fix it? it still appears even tho i already reinstall the game

**Comment by Athlon007** [comment]
MOP 3.4 (and newer) require MSCLoader.

You can still use MOP 3.3.10 with Mod Loader Pro.

**Comment by Estiloooo38A** [comment]
well iam using mscloader
