### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by xXbwarsXx** [Athlon007/MOP#47]
**Describe the bug**
When I load into MSC and continue the game it can't start and writes this:

15:05:12: Server Status: Online
15:05:12: Checking for new mods...
15:05:12: Looking for updates...
15:05:12: [WARNING] Downloading new rule file for DonnerTechRacing Turbocharger...
15:05:12: [SYSTEM] MOP 3.4.2 initialized!
15:05:14: [SYSTEM] Downloading completed!
15:05:14: Updating rules completed.
15:05:14: Found 1 rule file!
15:05:14: [SYSTEM] Loading 1/1 rule files done!
15:06:42: Loading MOP...
15:06:42: Found 156 bolts.
15:06:42: [WARNING] Only 156 out of expected 163 have been reset!
15:06:42: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:42: Vehicles initialized
15:06:42: World objects (1) loaded
15:06:42: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06_0.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:42: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06_1.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:42: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06_2.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:42: Finished applying fixes
15:06:42: World objects (2) loaded
15:06:42: Satsuma triggers loaded
15:06:43: Items class initialized
15:06:43: Hooked 9 save points!
15:06:43: Loading rules...
15:06:43: Rules loading complete!
15:06:43: Loading sectors...
15:06:43: Loaded 12 sectors
15:06:43: Toggling all to FALSE in mode ONLOAD
15:06:43: Toggled WORLD OBJECTS
15:06:43: Toggled ITEMS
15:06:43: Toggled KILJU
15:06:43: Toggled VEHICLES
15:06:43: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06_3.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:43: [SYSTEM] MOD LOADED SUCCESFULLY!
15:07:03: [ERROR] MOP failed to load in time. Please go into MOP settings and use "I found a bug" button.
15:07:04: [WARNING] MOP has stopped working! Restart attempt 1/3...
15:07:37: [WARNING] MOP has stopped working! Restart attempt 2/3...

**To Reproduce**
I start the game and this happens when I enter the world.
I have MOP version 3.4.2
MSC Loader 1.2.4
and these mods:
Showboltsize.dll
Satsumaturbocharger.dll
MOP.dll
Modshop.dll
HandBrakeMod.dll
Dynamite.dll
Cheatbox.dll
Backpack.dll

**Expected behavior**
I expected to start the game and have better FPS, but MOP failed to load

**Screenshots**
The "screenshot" is in "Describe the bug" (that is the log that id output)

**Game Version:** [My.Summer.Car.v04.03.2020]

**Mod Report:**
 Modern Optimization Plugin
Version: 3.4.2
MSC Mod Loader Version: 1.2.4
Date and Time: 2022-01-18T15:08:02Z
Windows 10 (10.0.19043) 64bit
Session ID: 247b1de2-6cde-48d5-836c-84a03392f55a
Game Restarts: 1
Game resolution: 1920x1080
Screen resolution: 1920x1080
Session Time: 0 Hours 1 Minutes 22 Seconds

=== MOP SETTINGS ===

ActiveDistance: 1
ActiveDistanceMultiplier: 1
PerformanceMode: Performance
LimitFramerate: False
FramerateLimiter: 60
ShadowDistance: 200
RunInBackground: True
DynamicDrawDistance: False
RulesAutoUpdate: True
VerifyRules: True
RulesAutoUpdateFrequency: 2
RuledDeleteAutomatically: False
DestroyEmptyBottles: True
DisableEmptyItems: False
ToggleVehiclePhysicsOnly: False
IgnoreModVehicles: False
CustomRuleFile: False

=== GAME DATA ===

PlayerPosition: (-8.1, -0.3, 11.0)
PlayerHasHayosikoKey: False
IsPlayerInCar: False
IsPlayerInSatsuma: False
DrawDistance: 3000
CanTriggerStatus: Found (JOBS/HouseDrunk/BeerCampOld/BeerCamp/KiljuBuyer/CanTrigger)
IsTrailerAttached: False
AverageFramerate: 20 FPS

=== MESSAGES ===

15:05:12: Server Status: Online
15:05:12: Checking for new mods...
15:05:12: Looking for updates...
15:05:12: [WARNING] Downloading new rule file for DonnerTechRacing Turbocharger...
15:05:12: [SYSTEM] MOP 3.4.2 initialized!
15:05:14: [SYSTEM] Downloading completed!
15:05:14: Updating rules completed.
15:05:14: Found 1 rule file!
15:05:14: [SYSTEM] Loading 1/1 rule files done!
15:06:42: Loading MOP...
15:06:42: Found 156 bolts.
15:06:42: [WARNING] Only 156 out of expected 163 have been reset!
15:06:42: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:42: Vehicles initialized
15:06:42: World objects (1) loaded
15:06:42: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06_0.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:42: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06_1.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:42: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06_2.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:42: Finished applying fixes
15:06:42: World objects (2) loaded
15:06:42: Satsuma triggers loaded
15:06:43: Items class initialized
15:06:43: Hooked 9 save points!
15:06:43: Loading rules...
15:06:43: Rules loading complete!
15:06:43: Loading sectors...
15:06:43: Loaded 12 sectors
15:06:43: Toggling all to FALSE in mode ONLOAD
15:06:43: Toggled WORLD OBJECTS
15:06:43: Toggled ITEMS
15:06:43: Toggled KILJU
15:06:43: Toggled VEHICLES
15:06:43: [WARNING] An error has occured. The log file has been saved folder into:

F:/Játékok/My Summer Car/My.Summer.Car.v04.03.2020//MOP_Logs/MOP_Crash_2022-01-18-15-06_3.txt.

Please go into MOP Settings and click "<b>I found a bug</b>" button, in order to generate the bug report and then follow the instructions.

You can continue playing.
15:06:43: [SYSTEM] MOD LOADED SUCCESFULLY!
15:07:03: [ERROR] MOP failed to load in time. Please go into MOP settings and use "I found a bug" button.
15:07:04: [WARNING] MOP has stopped working! Restart attempt 1/3...
15:07:37: [WARNING] MOP has stopped working! Restart attempt 2/3...

=== MODS (9) ===

Console:
  ID: MSCLoader_Console
  Version: 1.2.4
  Author: piotrulos

Settings (Main):
  ID: MSCLoader_Settings
  Version: 1.2.4
  Author: piotrulos

Backpack:
  ID: Backpack
  Version: 1.0.14
  Author: UltraJohn

CheatBox:
  ID: CheatBox
  Version: 1.2.0
  Author: Roman266

Dynamite:
  ID: Dynamite
  Version: 0.2.3
  Author: zamp

Handbrake Mod:
  ID: handbrakemod
  Version: 1.4
  Author: tommojphillips

Shop Catalog - BETA:
  ID: ModsShop
  Version: 0.9.3
  Author: piotrulos

DonnerTechRacing Turbocharger:
  ID: SatsumaTurboCharger
  Version: 2.1.7
  Author: DonnerPlays

ShowBoltSize:
  ID: ShowBoltSize
  Version: 2.1
  Author: Lex (original by wolf_vx)

=== RULE FILES ===

SatsumaTurboCharger.mopconfig

[MOP Bug Report - 2022-01-18_15-08.zip](https://github.com/Athlon007/MOP/files/7889762/MOP.Bug.Report.-.2022-01-18_15-08.zip)

**Additional context**
I don't have anything else.

**Comment by Athlon007** [comment]
Sorry, but MOP does not work with pirated copies of the game.

Closing.
