### ISSUE TITLE
Grill fire bug

### ISSUE THREAD

**Issue by insus100** [Athlon007/MOP#49]
**Describe the bug**
Grill bugs out while lit outside the garage if you enter the garage.

**To Reproduce**
[Steps to reproduce the behavior:
1. Fill the charcoal grill with charcoal.
2. Place it on your roadway outside the house garage.
3. Start a fire.
4. Go inside the garage or house (so the lake water disappears)
5. Go to the grill and you'll see fire is started but it will never end and it won't create ashes.

**Expected behavior**
Grill should generate ashes after some time burning, even if you enter the house/garage.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 15.11.2019/Experimental]
Latest non experimental as of 22.01.2022

**Mod Report:**
n/a

**Additional context**
n/a
[output_log.txt](https://github.com/Athlon007/MOP/files/7918329/output_log.txt)

**Comment by Athlon007** [comment]
Hi, thanks for reporting the issue!

I've done some changes and now the grill will be enabled at all times if it's set on fire.

The change will be included in the next update.
