### ISSUE TITLE
jetski (mod) dissapears when far

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#5]
**Describe the bug**
the boat (jetski mod) disappears completely and the items fall into the lake
**To Reproduce**
1. install jetski mod
2. go on a far distance
3. return

**Expected behavior**
the jetski would still be there
**Screenshots**

**Game Version:**23.12.2019 modloader 1.1.5
**Mod Report:**
 [Go into mod settings and click "Generate mod report", and paste the content here]
[MOP_REPORT.txt](https://github.com/Athlon007/MOP/files/4030063/MOP_REPORT.txt)

**Additional context**

**Comment by Athlon007** [comment]
Fixed in Beta 1.5.
