### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DaniUY** [Athlon007/MOP#50]
**Describe the bug**
[I am getting this error when entering the game and my items in the game are not loading properly.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![IMG_20220125_202401](https://user-images.githubusercontent.com/98481989/151215737-09e02f99-ed6e-4ba2-9c1b-526ec2a4831f.jpg)

**Game Version:** [24.03.2021]

**Mod Report:**
 [Go into mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-01-26_20-32.zip](https://github.com/Athlon007/MOP/files/7943880/MOP.Bug.Report.-.2022-01-26_20-32.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
You're using an outdated version of the MOP, **AND** you are using a pirated copy of MSC.
