### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by prosguys789789** [Athlon007/MOP#51]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 1
[MOP Bug Report - 2022-02-03_18-46.zip](https://github.com/Athlon007/MOP/files/7996063/MOP.Bug.Report.-.2022-02-03_18-46.zip)
5.11.2019/Experimental]

**Mod Report:**
 [Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
You're using a pirated copy.
