### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ZeBenga** [Athlon007/MOP#52]
**Describe the bug**
It says that the game does not fully load Satsuma and to restart the game, I do that but it still does the same thing

**To Reproduce**

[Steps to reproduce the behavior:
1. Go to 'continue
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 25.01.2022

**Mod Report:**

[MOP Bug Report - 2022-02-05_00-03.zip](https://github.com/Athlon007/MOP/files/8007273/MOP.Bug.Report.-.2022-02-05_00-03.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Hi there, sorry for the late reply.

Is the issue still present in the latest version of MOP?
