### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by KILLSwitch6985** [Athlon007/MOP#58]
**Describe the bug**
Everytime i start the game it says MOP took to long to start and to click i found a bug

**To Reproduce**
Literally hit continue and wait

**Expected behavior**
It to open and work

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

![image](https://user-images.githubusercontent.com/103542357/163071360-d2340248-b4c8-41d4-9674-192b6e5e6810.png)
[MOP Bug Report - 2022-04-12_16-29.zip](https://github.com/Athlon007/MOP/files/8477108/MOP.Bug.Report.-.2022-04-12_16-29.zip)

**Comment by Athlon007** [comment]
Hi there!

Thanks for reporting the issue. Could you please also pack your Mods folder and upload it here? Thanks.

**Comment by Athlon007** [comment]
The latest Beta should fix this issue. Please try it.

**Comment by Athlon007** [comment]
Fixed in 3.6.1.
