### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Alebetes** [Athlon007/MOP#62]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 15.11.2019/Experimental]

**Mod Report:**
 [Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
[MOP Bug Report - 2022-04-16_12-37.zip](https://github.com/Athlon007/MOP/files/8499723/MOP.Bug.Report.-.2022-04-16_12-37.zip)

Hello, I do not know how this work, but I hope it does, not too familiar with Github. Anyway, the bug here is that it takes longer than usual to load. That's all.

**Comment by Athlon007** [comment]
This has been fixed in MOP 3.6.1.
