### ISSUE TITLE
Game Reloading itself caused by MOP

### ISSUE THREAD

**Issue by Estiloooo38A** [Athlon007/MOP#64]
**Describe the bug**
The game reload itself right after it loads  using MOP

**To Reproduce**
[Steps to reproduce the behavior:
1. Continue
2. Wait for loading 
3. And then it reloads itself right after it loads

**Expected behavior**
Game Reloads Itself and after the next load the game wont load so its just stuck on the loading menu 

**Game Version:**  Latest Version (as in 20/04/2022)

**Mod Report:**
 
[MOP Bug Report - 2022-04-20_21-55.zip](https://github.com/Athlon007/MOP/files/8522794/MOP.Bug.Report.-.2022-04-20_21-55.zip)

Apologize for my bad english.

**Comment by Athlon007** [comment]
Hi there,
this seems like to be a mod conflict issue. Unfortunately there is so many mods you got, that it would take me ages to find out which mod is causing this conflict.

The only way is to disable mods one-by-one, until that issue doesn't happen.

**Comment by Athlon007** [comment]
Hi there,
I tried replicating it on your save file - but I couldn't replicate it. It _might_ be something related to a mod conflict, although I'm not sure.

Could you please do this:

1. Start the game and press "Continue"
2. When the game reloads, let it loop like that 2-3 times.
3. Force quit the game and immediately after that, go into My Summer Car's folder and upload the "output_log.txt" file over here.

**Comment by Estiloooo38A** [comment]
[output_log.txt](https://github.com/Athlon007/MOP/files/8537251/output_log.txt)

Also The bug report after i loaded the game
[MOP Bug Report - 2022-04-22_12-35.zip](https://github.com/Athlon007/MOP/files/8537254/MOP.Bug.Report.-.2022-04-22_12-35.zip)

**Comment by Athlon007** [comment]
Should be fixed in the MOP 3.6.3.
