### ISSUE TITLE
Oil Filter Keeps disappering

### ISSUE THREAD

**Issue by Guibbson** [Athlon007/MOP#65]
Describe the bug
My Oil Filter keeps disappering after some time of gameplay if MOP settings is other than safe

To Reproduce
1. Take satsuma and drive for some time
2. The oil filter will eventualy disappear(Usually happens on Highway)

Game Version: Last Version (15/04/2022) VersionID: 8495002

Mod Report:
 
[MOP Bug Report - 2022-04-20_19-06.zip](https://github.com/Athlon007/MOP/files/8525868/MOP.Bug.Report.-.2022-04-20_19-06.zip)

Sorry for bad english

**Comment by Athlon007** [comment]
Hi there,
this seems like to be a mod conflict issue. Unfortunately there is so many mods you got, that it would take me ages to find out which mod is causing this conflict.

The only way is to disable mods one-by-one, until that issue doesn't happen.

**Comment by Guibbson** [comment]
Thanks, i will try that

**Comment by Guibbson** [comment]
Turns out that it was FifhtGear mod, disabled it and the error stop ocurring

**Comment by Athlon007** [comment]
Interesting, I'll look into it. Thanks for the report!

**Comment by Guibbson** [comment]
You're welcome
