### ISSUE TITLE
MOP crashing on during loading

### ISSUE THREAD

**Issue by poom7504** [Athlon007/MOP#66]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
[MOP Bug Report - 2022-04-24_18-30.zip](https://github.com/Athlon007/MOP/files/8549564/MOP.Bug.Report.-.2022-04-24_18-30.zip)

4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 15.11.2019/Experimental]

**Mod Report:**
 [Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Hi there,
In the future, please fill-out the bug report template.

**Comment by Athlon007** [comment]
Fixed in 3.6.3
