### ISSUE TITLE
MOP doesn't work and an error is visible in the console.

### ISSUE THREAD

**Issue by WojasOfficial** [Athlon007/MOP#67]
**Describe the bug**
MOP crashes when loading a save and an error is visible in the console.

**To Reproduce**
[Steps to reproduce the behavior:
1. load a save

**Expected behavior**
I expected the mod to work and not crash.

**Screenshots**
![Screenshot 2022-04-27 195810](https://user-images.githubusercontent.com/104523825/165590379-aef2a173-e0a2-427b-b318-fde42f286f0a.png)

**Game Version:** [04.04.2022]

**Mod Report:**
 [MOP Bug Report - 2022-04-27_19-51.zip](https://github.com/Athlon007/MOP/files/8575347/MOP.Bug.Report.-.2022-04-27_19-51.zip)

**Additional context**
I can give the crash log: 
[MOP_Crash_2022-04-27-19-49_0.txt](https://github.com/Athlon007/MOP/files/8575356/MOP_Crash_2022-04-27-19-49_0.txt)

**Comment by Athlon007** [comment]
Hi, this MOP version seems to have some compatibility issues with DonnerTech mods.
What you could try is using the latest Beta version: https://github.com/Athlon007/MOP/releases/tag/3.6.3-beta_1

Cheers!

**Comment by WojasOfficial** [comment]
> Hi, this MOP version seems to have some compatibility issues with DonnerTech mods. What you could try is using the latest Beta version: https://github.com/Athlon007/MOP/releases/tag/3.6.3-beta_1
> 
> Cheers!

Thank you

**Comment by Athlon007** [comment]
MOP 3.6.3 has been released with the fix.
