### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by foorame** [Athlon007/MOP#70]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
[MOP Bug Report - 2022-05-05_22-49.zip](https://github.com/Athlon007/MOP/files/8635774/MOP.Bug.Report.-.2022-05-05_22-49.zip)

4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 15.11.2019/Experimental]

**Mod Report:**
 [Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Hi there!
For whatever reason, MOP cannot access your game's save files. To fix that go to the folder where your save files are located (C:\Users\your user name\AppData\LocalLow\Amistech\My Summer Car), right click on the defaultES2File.txt, then at the bottom see if the file is set to read-only (if so, uncheck it). Repeat for items.txt.
