### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by badsantaslay** [Athlon007/MOP#75]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 15.11.2019/Experimental]

**Mod Report:**
 [Go into mod settings and click "I FOUND A BUG", and 
[MOP Bug Report - 2022-05-08_12-37.zip](https://github.com/Athlon007/MOP/files/8646838/MOP.Bug.Report.-.2022-05-08_12-37.zip)
paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Pirated game copies are not supported.
