### ISSUE TITLE
MSCLoader V1.2.5 - Minor "MOP Crash" Bug Report (Game still running fine though)

### ISSUE THREAD

**Issue by Satsumarider** [Athlon007/MOP#79]
**Describe the bug**
A minor error that keeps appearing on the MSCLoader V1.2.5 command line after loading in, something to do with the Satsuma. I'm sure one of the MOP Logs will elaborate.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load up the save via the 'Continue' button
2. See error]

**Expected behaviour**
No error to appear, happy days :)

**Screenshots**

![image](https://user-images.githubusercontent.com/83514952/167895000-cfa2cb2d-8d89-4a94-b880-649798f027f1.png)

**Mod Report:**

[MOP Bug Report - 2022-05-11_17-00.zip](https://github.com/Athlon007/MOP/files/8671562/MOP.Bug.Report.-.2022-05-11_17-00.zip)

**Additional context**
At long last, I have mustered up the courage to revert back to the tried and true MSCLoader, after the beloved ModLoader Pro was discontinued.

Afterwards, I loaded up the game, to see the MSCLoader command line to open up. Yellow text, on about MOP crashing.

What a strange crash, The game was smooth, in fact, everything seemed to be working fine, MOP was still working.

Even the command line message said that I could continue playing.

Strange... Although not a major problem by any means, it's just one extra step every time I load up, pressing backquote to close the command line.

**Comment by Athlon007** [comment]
Hi there, sorry for a late reply.
It definitely seems like there is some mod conflict there (probably some mod that has something to do with the Satsuma). The only option is to disable all mods (or at least the ones that interact with Satsuma), then enable them one-by-one and see which one causes the issue.
