### ISSUE TITLE
mop drops an error when started

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#8]
after the update, the mop mod will give an error once i started 
all you need to reproduce is just to load the mop 
here is the log generated file
[MOP_LOG.txt](https://github.com/Athlon007/MOP/files/4046644/MOP_LOG.txt)

if is nothing to worry about I will close the issue, i removed the mop and report this issue just in case if it broke my game permanently (like the cd radio)

**Comment by Athlon007** [comment]
That log is from Beta 1.1.3, and the current newest is Beta 1.5

**Comment by Athlon007** [comment]
I accidentally uploaded the old version Beta 1.1.3. I just reuploaded it, so please go and download it now. I'm really sorry.
