### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by gopnikblin** [Athlon007/MOP#81]
**Describe the bug**
MOP Doesn't load correctly when I load into my save as seen in the console.

**To Reproduce**
[Steps to reproduce the behavior:
1. Load into save.
2. Wait till loading is finished.
3. Console will pop up with the error of MOP not loading correctly and trying to restart.
4. See error]

**Expected behavior**
Just MOP not loading and trying to restart but failing.

**Screenshots**
![image](https://user-images.githubusercontent.com/75844210/168477546-93f74081-8c10-4710-b939-b514d52b519c.png)
![image](https://user-images.githubusercontent.com/75844210/168477550-eb338fcb-929c-4ff0-96e2-eb30bcd23d79.png)

**Mod Report:**
[MOP Bug Report - 2022-05-15_22-12.zip](https://github.com/Athlon007/MOP/files/8695127/MOP.Bug.Report.-.2022-05-15_22-12.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
It seems like this is caused by some mod incompatibility. Try disabling all mods (excluding MOP) and enable them one-by-one.

**Comment by Athlon007** [comment]
Closed due to inactivity.
