### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by cemgorey** [Athlon007/MOP#82]
hey, MOP stopped working just loading the game. everything else is in the zip.

**Comment by cemgorey** [comment]
[MOP Bug Report - 2022-05-16_15-15.zip](https://github.com/Athlon007/MOP/files/8699954/MOP.Bug.Report.-.2022-05-16_15-15.zip)

**Comment by Athlon007** [comment]
Hi there, it seems like it's a mod compatibility issue.

I would suggest disabling all mods (except for MOP), then enable mods one-by-one, to see which one causes the issue.

**Comment by Athlon007** [comment]
Closed due to inactivity.
