### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Monkeyboyyyy** [Athlon007/MOP#84]
**Describe the bug**
[When i load the game mop fails to load. It says: Mop failed to load in time. Please go into MOP settings and use "i found a bug button. ]

**To Reproduce**
[Steps to reproduce the behavior:
1. Go to ' start game'
2. Click on 'nothing.'
3. Scroll down to ' nothing'
4. See error]

**Expected behavior**
[I epxpected MOP to load as it should and.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[ [MOP Bug Report - 2022-05-26_21-29.zip](https://github.com/Athlon007/MOP/files/8781621/MOP.Bug.Report.-.2022-05-26_21-29.zip)]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Hi, it seems like there might be some issue with mod conflict, or your game is corrupted.
I would advise you to verify game files integrity first. If that doesn't help, try disabling all mods (except for MOP) and enable them one-by-one, to see which causes the issue.

**Comment by Athlon007** [comment]
Closed due to inactivity.
