### ISSUE TITLE
Bug Report - Computer shuts down

### ISSUE THREAD

**Issue by RBRobin** [Athlon007/MOP#85]
**Describe the bug**
Was downloading rally95.exe from con-line. Whilst waiting decided to do some delivery jobs (https://www.nexusmods.com/mysummercar/mods/162) and when I came back to the house (around 1 hour in real-time) the Computer was off. I had electric & telephone bills paid before leaving, fridge & lights all still worked, no blown fuses - I could also switch the computer back on.

Thought this was MOP disabling the PC when out of range, so tried to make my own custom rule file to ignore the computer.

This is what's throwing the errors - I'm guessing something to do with [2.9.8 (09.06.2020)](http://athlon.kkmr.pl/mop/wiki/#/changelog?id=_298-09062020)

I have removed the custom rule file and not getting the MOP errors, so obviously something either wrong with 

**To Reproduce**
1 - start pc and go through the steps to start downloading rally95.exe
2 - check that phonebill / electric bills are paid
3 - leave the area to do jobs / shop / whatever
4 - come home and check if computer is still on - it is not.

[MOP Bug Report - 2022-05-28_12-33.zip](https://github.com/Athlon007/MOP/files/8791051/MOP.Bug.Report.-.2022-05-28_12-33.zip)

**Expected behavior**
I expected the PC to be on when I got home - it wasn't.
I was hoping that the custom rule file with ignore:COMPUTER would fix the issue, but is what is giving the bug report - I am not expecting this bit to be fixed.

**Screenshots**
N/A

**Mod Report:**
[MOP Bug Report - 2022-05-28_12-33.zip](https://github.com/Athlon007/MOP/files/8791063/MOP.Bug.Report.-.2022-05-28_12-33.zip)

**Additional context**
[Add any other context about the problem here.]

I've also found that running the console and typing 
mod delete custom
throws another error that custom.mopconfig does not exist

**Comment by Athlon007** [comment]
Hi there, sorry for a late response.
I've indeed found an issue with custom rule files causing the game to crash.

As for the Computer turning off, MOP checks if the computer is running and does not disable it if so. Are you sure there wasn't a thunderstorm while you were outside? They cause power outages, which could make your computer shut down.

**Comment by Athlon007** [comment]
Fixed in 3.7.1.
