### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by jimmuel06** [Athlon007/MOP#87]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]
[MOP Bug Report - 2022-05-31_09-45.zip](https://github.com/Athlon007/MOP/files/8801164/MOP.Bug.Report.-.2022-05-31_09-45.zip)
[MOP Bug Report - 2022-05-31_09-45.zip](https://github.com/Athlon007/MOP/files/8801166/MOP.Bug.Report.-.2022-05-31_09-45.zip)

**Comment by Athlon007** [comment]
Sorry, but illegally obtained game copies are not supported!
