### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Aganek123** [Athlon007/MOP#88]
[MOP Bug Report - 2022-06-04_15-31.zip](https://github.com/Athlon007/MOP/files/8837697/MOP.Bug.Report.-.2022-06-04_15-31.zip)

![image](https://user-images.githubusercontent.com/106871117/171999042-f4cdb9be-1d02-4b2a-a656-5d4a5de1a147.png)

**Comment by Athlon007** [comment]
Hi there,
It seems to be a mod conflict problem. The best solution is to disable all mods (except for MOP) and try enabling every single one-by-one, until you find the one that's causing the problem.
