### ISSUE TITLE
MSC says the mod version is 1.1.3, game not saving

### ISSUE THREAD

**Issue by NeniTele** [Athlon007/MOP#9]
MSC claims mod version 1.1.3 and the game won't save.

What I did:
 - Downloaded version 1.5 from here
 - Reinstalled mod loader including full cleaning of mods folder
 - Pasted mod to new mods folder (no other mods in my game)
 - Tried to download from RaceDepartment, same issue

Using experimental branch of the game, the mod was working fine on version 1.4.1 few hours ago.

(might be related to the issue opened by tonimark, who can't load the game and log for version 1.1.3 is produced)

**Comment by Athlon007** [comment]
I accidentally uploaded the old version 1.1.3. I'm really sorry for that.

**Comment by NeniTele** [comment]
That was fast. Thank you!
