### ISSUE TITLE
MOP crashes when house is burned down

### ISSUE THREAD

**Issue by twitchlavender** [Athlon007/MOP#90]
[MOP Bug Report - 2022-06-05_18-49.zip](https://github.com/Athlon007/MOP/files/8840459/MOP.Bug.Report.-.2022-06-05_18-49.zip)

**Comment by Athlon007** [comment]
Hi there, it seems like either your game or MOP is corrupted. Try the following:

1. Check game files integrity with Steam
2. Download a fresh copy of MOP
3. Reinstall MSCLoader

**Comment by Athlon007** [comment]
Fixed in 3.7.
