### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DaewooGamingFI** [Athlon007/MOP#91]
**Describe the bug**
The  flatbed trailer keeps disappearing. It is near the house and sometimes when I go away from it when it is attached to the tractor it disappears and I have to use MSC editor to make it appear again. MSC editor tells me that the trailer is a few meters away from where it should be and under the map. This has happened to me twice and both times MSC editor says it is in the following coordinates 1.0431243181, -0.4776276648, -4.731926918.  the trailer should be here -12.471, 0.341, 31.291

**To Reproduce**
[Steps to reproduce the behavior:
1. attach the trailer to the tractor
2. walk away from it until the tractor and the trailer disappears
3. walk back to where the trailer should be
4. the trailer appears when you get closer
5. the trailer disappears when you are right next to it

**Expected behavior**
It should appear again when I go near where it should be

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Repo
[MOP Bug Report - 2022-06-13_17-27.zip](https://github.com/Athlon007/MOP/files/8891983/MOP.Bug.Report.-.2022-06-13_17-27.zip)
rt:**

**Additional context**
the trailer only disappears when it is attached to the tractor.

**Comment by Athlon007** [comment]
Hi there. Thanks for reporting this problem. It will be fixed in the next version of MOP :)

**Comment by Athlon007** [comment]
Fixed in 3.7.
