### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by vipsrbfanpage** [Athlon007/MOP#93]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]
Basically, it tried to restart 3 times but failed. I don't know whats happening.
**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-06-16_14-42.zip](https://github.com/Athlon007/MOP/files/8918931/MOP.Bug.Report.-.2022-06-16_14-42.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Sorry, but illegally obtained game copies are not supported!
