### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by BSalgad0** [Athlon007/MOP#94]
Hello there, 

In the attachement there is a screenshot of the cup bug and file report.

Bugs:

Cup physics don't work, and items fall trough the floor of all cars.

Also trailer of tractor bugs and dissapears for no reason.

[MOP Bug Report - 2022-06-21_23-10.zip](https://github.com/Athlon007/MOP/files/8953084/MOP.Bug.Report.-.2022-06-21_23-10.zip)
![Captura de ecrã 2022-06-21 231147](https://user-images.githubusercontent.com/107504359/174905584-8f3c69a1-b741-4335-9da3-2dee2a1974f5.png)

Thank you for your time.

**Comment by Athlon007** [comment]
When exactly does the falling of objects through cars happen?

**Comment by BSalgad0** [comment]
I'm gonna give you an example, When I have a car in the city with a beer case and shopping bag, I go to my home and come back with another car to the city and the stuff goes trough the floor of the car that had those stuff inside it.

I posted images with the mods I use if it helps.

![image](https://user-images.githubusercontent.com/107504359/174910495-4f5c39be-e1e6-4027-ac5c-e6c78cf4a01b.png)

![image](https://user-images.githubusercontent.com/107504359/174910510-d8633be7-30a1-4325-993c-cac1c646c95d.png)

![image](https://user-images.githubusercontent.com/107504359/174910528-10f571c6-c00b-41b3-a4a6-50922cd1bd17.png)

**Comment by Athlon007** [comment]
Does it still happen with Hayosiko?
For this version of MOP, I made a solution for the stuff not falling out of the cars, but I've only applied it for Hayosiko for now.

**Comment by BSalgado1998** [comment]
Well I'm gonna be honest haven't seen if it happens on Hayosiko, I'm gonna test it then I will give you feedback later.

Are you testing if the solution works then you will apply everywhere?

**Comment by BSalgad0** [comment]
Well I'm gonna be honest haven't seen if it happens on Hayosiko, I'm gonna test it then I will give you feedback later.

Are you testing if the solution works then you will apply everywhere

**Comment by Athlon007** [comment]
For the moment, yes. 

I want to make sure that it doesn't break the van, and that it actually solves the issue.

**Comment by BSalgado1998** [comment]
Are you aware of the trailer bug? The tractor trailor bugs, diseapears and MOP detects the issue but then I say MOP to fix it and it doesn't solve it, did you also fix that this version?

**Comment by BSalgad0** [comment]
After a couple hours of playing I can confirm the things don't fall on van and ruscko, But I found a new game breaking bug which is the one that jokke disseapears and there is always a party in is house and you can never keep Spirit bottle.

And the cup bug persists on teemo coffee, thank you for your time.

**Comment by Athlon007** [comment]
Does it also happen to Satsuma?

**Comment by BSalgado1998** [comment]
It's only on the truck and tractor

**Comment by BSalgado1998** [comment]
Just remembered it also falls trough the boat

**Comment by Athlon007** [comment]
Fixed in 3.7.1.
