### ISSUE TITLE
Bug Report satsuma fuel line leaks fuel if the mop load and unloads satsuma

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#95]
**Describe the bug**
[A clear and concise description of what the bug is.]
the satsuma line would mostly start to leak , if the save is also load and unloaded
**To Reproduce**
[Steps to reproduce the behavior:
1. Go to 'start by untightening fuel line bolt (without mop) and save game'
2. Click on 'install mop'
3. Scroll down to 'reload save and tight the fuel line bolt then save again'
4. See error]load the save the satsuma will keep on leaking

**Expected behavior**
[A clear and concise description of what you expected to happen.]
the fuel line would not leak
**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-06-23_22-22.zip](https://github.com/Athlon007/MOP/files/8970283/MOP.Bug.Report.-.2022-06-23_22-22.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment]
Hi, I've checked and there is in fact an issue with MOP.

I've also found another issue with your save file. For some reason on your save file, the "tightness" state of "fuelline" ranges from -8 to 0, while it should be ranging from 0 to 8. That means your fuel line will be always leaking, no matter what.

To fix that, you can use MSCEditor. I'll also add a fix for that in next MOP version.

**Comment by tonimark** [comment]
i actually fixed ago using MSC editor but at least I know it is a mop issue now
