### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Groch123** [Athlon007/MOP#97]
[MOP Bug Report - 2022-07-02_14-49.zip](https://github.com/Athlon007/MOP/files/9032966/MOP.Bug.Report.-.2022-07-02_14-49.zip)
I DONT KNOW ЧТО ЭТО ЗА ХУЙНЯ!!!!!!!!!!

**Comment by Athlon007** [comment]
1.) Your save is absolutely broken (can't even load it in MSCEditor).
2.) You are using a pirated copy of the game.
