### ISSUE TITLE
bug report kilju bucket lid will load/unload inproperly

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#99]
**Describe the bug**
[A clear and concise description of what the bug is.]
if you place the kilju bucket in a weird position it will jump around and in stages of loading/unloading it, the lid will rotate to a weird
**To Reproduce**
[Steps to reproduce the behavior:
1. get the kilju bucket
2. put the lid in the kilju bucket
3. move the bucket (with the lid) in a weird location (in my case inside jokke's apartment 
4. move way and comeback so the mop can load and unload the bucket
5.see error
**Expected behavior**
[A clear and concise description of what you expected to happen.]
the lid in the bucket would stay intact (normal)
**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![MSC_Screenshot](https://user-images.githubusercontent.com/17166550/177047908-4905d95c-c33e-4d3e-b8f8-04dedbc37e02.png)

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]
[MOP Bug Report - 2022-07-03_19-04.zip](https://github.com/Athlon007/MOP/files/9035111/MOP.Bug.Report.-.2022-07-03_19-04.zip)

**Additional context**
[Add any other context about the problem here.]

**Comment by tonimark** [comment]
the issue got worse after a while the bucket's lid would detach, Idk if this is a mop issue but it ruined a kilju branch

**Comment by Athlon007** [comment]
Fix 3.8
